/* Automatically generated struct frame header */
/* Generated by 0.0.1 at Fri Feb  7 20:19:06 2025. */

#pragma once
#pragma pack(1)
#include "serial_frame.h"
/* Enum definitions */
typedef enum _biostream_adc_sampling_frequency {
    FREQ_1000 = 0,
    FREQ_2000 = 1,
    FREQ_4000 = 2,
    FREQ_8000 = 3,
    FREQ_16000 = 4
} biostream_adc_sampling_frequency;
typedef uint8_t biostream_adc_sampling_frequency;

//enum before comment
typedef enum _biostream_trans_impedance_gain {
    R_10 = 0,
    R_100 = 1,
    R_1K = 2,
//Enum inside comment
    R_10K = 3
} biostream_trans_impedance_gain;
typedef uint8_t biostream_trans_impedance_gain;

/* Struct definitions */
//2nd line comment
typedef struct _biostream_raw_data2 {
//In Message comment
    float ref_v;
    float drn_c;
//Field comment
    float src_v;
    float drn_v;
    float gte_v;
    float phs_v;
    biostream_raw_data gte_c;
    float temp;
    float time;
} biostream_raw_data2;

#define biostream_raw_data2_max_size 68;
#define biostream_raw_data2_msgid 1
MESSAGE_HELPER(biostream_raw_data2, 68, 1);



typedef struct _biostream_raw_data {
    float ref_v;
    float drn_c;
    float src_v;
    float drn_v;
    float gte_v;
    float phs_v;
    float gte_c;
    float temp;
    float time;
} biostream_raw_data;

#define biostream_raw_data_max_size 36;
#define biostream_raw_data_msgid 1
MESSAGE_HELPER(biostream_raw_data, 36, 1);



typedef struct _biostream_adc_command {
    boolean enable;
    biostream_adc_sampling_frequency samplig_freq;
    uint8_t over_sampling_rate;
    biostream_trans_impedance_gain drain_res;
    biostream_trans_impedance_gain gate_res;
} biostream_adc_command;

#define biostream_adc_command_max_size 5;
#define biostream_adc_command_msgid 112
MESSAGE_HELPER(biostream_adc_command, 5, 112);




uint8_t get_message_length(uint8_t msg_id){
 switch (msg_id)
 {
  case biostream_raw_data2_msgid: return biostream_raw_data2_max_size;
  case biostream_raw_data_msgid: return biostream_raw_data_max_size;
  case biostream_adc_command_msgid: return biostream_adc_command_max_size;
  default: break;
 } return 0;
}
