# Automatically generated struct frame header 
# Generated by 0.0.1 at Tue Aug 12 03:02:59 2025. 

from structured import *
from enum import Enum

# Enum definitions
class MylVehicleType(Enum):
    TYPE_UNSPECIFIED = 0
    TYPE_ROVER = 1
    TYPE_BOAT = 2
    TYPE_FW = 3
    TYPE_MR = 4
    TYPE_CAR = 5

# Struct definitions 
class MylVehicleposition(Structured):
    msg_size = 20
    msg_id = 1
    lat: float64
    lon: float64
    alt: float32

    def __str__(self):
        out = "position Msg, ID 1, Size 20 \n"
        out += f"lat = {self.lat}\n"
        out += f"lon = {self.lon}\n"
        out += f"alt = {self.alt}\n"
        out += "\n"
        return out


#//Used for sending robot pose
class MylVehiclepose(Structured):
    msg_size = 26
    msg_id = 2
#//Used for sending roll
    roll: float32
#// Used for sending pitch
    pitch: float32
    yaw: float32
    roll_rate: float32
    pitch_rate: float32
    yaw_rate: float32
    test: int16

    def __str__(self):
        out = "pose Msg, ID 2, Size 26 \n"
        out += f"roll = {self.roll}\n"
        out += f"pitch = {self.pitch}\n"
        out += f"yaw = {self.yaw}\n"
        out += f"roll_rate = {self.roll_rate}\n"
        out += f"pitch_rate = {self.pitch_rate}\n"
        out += f"yaw_rate = {self.yaw_rate}\n"
        out += f"test = {self.test}\n"
        out += "\n"
        return out


class MylVehicleheartbeat(Structured):
    msg_size = 5
    msg_id = 3
    type: uint8 #MylVehicleType
    id: int32

    def __str__(self):
        out = "heartbeat Msg, ID 3, Size 5 \n"
        out += f"type = {self.type}\n"
        out += f"id = {self.id}\n"
        out += "\n"
        return out


class MylVehicleheartbeat2(Structured):
    msg_size = 8
    msg_id = 4
    test: float32
    id3: int32

    def __str__(self):
        out = "heartbeat2 Msg, ID 4, Size 8 \n"
        out += f"test = {self.test}\n"
        out += f"id3 = {self.id3}\n"
        out += "\n"
        return out



myl_vehicle_definitions = {
    1: MylVehicleposition,
    2: MylVehiclepose,
    3: MylVehicleheartbeat,
    4: MylVehicleheartbeat2,
}
