/* Automatically generated struct frame header */
/* Generated by 0.0.1 at Tue Aug 12 03:02:59 2025. */

#pragma once
#pragma pack(1)
#include "struct_frame.h"
/* Enum definitions */
typedef enum MylVehicleType {
    TYPE_UNSPECIFIED = 0,
    TYPE_ROVER = 1,
    TYPE_BOAT = 2,
    TYPE_FW = 3,
    TYPE_MR = 4,
    TYPE_CAR = 5
} MylVehicleType;
typedef uint8_t MylVehicleType_t;

/* Struct definitions */
typedef struct MylVehicleposition {
    double lat;
    double lon;
    float alt;
} MylVehicleposition;

#define MYL_VEHICLE_POSITION_MAX_SIZE 20
#define MYL_VEHICLE_POSITION_MSG_ID 1
MESSAGE_HELPER(myl_vehicle_position, MylVehicleposition, 20, 1);



//Used for sending robot pose
typedef struct MylVehiclepose {
//Used for sending roll
    float roll;
// Used for sending pitch
    float pitch;
    float yaw;
    float roll_rate;
    float pitch_rate;
    float yaw_rate;
    int16_t test;
} MylVehiclepose;

#define MYL_VEHICLE_POSE_MAX_SIZE 26
#define MYL_VEHICLE_POSE_MSG_ID 2
MESSAGE_HELPER(myl_vehicle_pose, MylVehiclepose, 26, 2);



typedef struct MylVehicleheartbeat {
    MylVehicleType_t type;
    int32_t id;
} MylVehicleheartbeat;

#define MYL_VEHICLE_HEARTBEAT_MAX_SIZE 5
#define MYL_VEHICLE_HEARTBEAT_MSG_ID 3
MESSAGE_HELPER(myl_vehicle_heartbeat, MylVehicleheartbeat, 5, 3);



typedef struct MylVehicleheartbeat2 {
    float test;
    int32_t id3;
} MylVehicleheartbeat2;

#define MYL_VEHICLE_HEARTBEAT2_MAX_SIZE 8
#define MYL_VEHICLE_HEARTBEAT2_MSG_ID 4
MESSAGE_HELPER(myl_vehicle_heartbeat2, MylVehicleheartbeat2, 8, 4);




bool get_message_length(size_t msg_id, size_t* size){
 switch (msg_id)
 {
  case MYL_VEHICLE_POSITION_MSG_ID: *size = MYL_VEHICLE_POSITION_MAX_SIZE; return true;
  case MYL_VEHICLE_POSE_MSG_ID: *size = MYL_VEHICLE_POSE_MAX_SIZE; return true;
  case MYL_VEHICLE_HEARTBEAT_MSG_ID: *size = MYL_VEHICLE_HEARTBEAT_MAX_SIZE; return true;
  case MYL_VEHICLE_HEARTBEAT2_MSG_ID: *size = MYL_VEHICLE_HEARTBEAT2_MAX_SIZE; return true;
  default: break;
 } return false;
}
