// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 16:33:01 2025.

const { createFrameMsgInfo, fletcher_checksum } = require('./frame_base');

// =============================================================================
// BasicMinimal Frame Format
// =============================================================================

const BasicMinimalParserState = {
    LOOKING_FOR_START1: 0,
    LOOKING_FOR_START2: 1,
    GETTING_MSG_ID: 2,
    GETTING_PAYLOAD: 3
};

/**
 * BasicMinimal - Frame format parser and encoder
 */
class BasicMinimal {
    static START_BYTE1 = 0x90;
    static START_BYTE2 = 0x70;
    static HEADER_SIZE = 3;
    static FOOTER_SIZE = 0;
    static OVERHEAD = 3;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
    }

    reset() {
        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicMinimalParserState.LOOKING_FOR_START1:
                if (byte === BasicMinimal.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMinimalParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicMinimalParserState.LOOKING_FOR_START2:
                if (byte === BasicMinimal.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicMinimalParserState.GETTING_MSG_ID;
                } else if (byte === BasicMinimal.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMinimalParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicMinimalParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                if (this.get_msg_length) {
                    const msg_length = this.get_msg_length(byte);
                    if (msg_length !== undefined) {
                        this.packet_size = BasicMinimal.OVERHEAD + msg_length;
                        this.state = BasicMinimalParserState.GETTING_PAYLOAD;
                    } else {
                        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                    }
                } else {
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicMinimalParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    result.valid = true;
                    result.msg_id = this.msg_id;
                    result.msg_len = this.packet_size - BasicMinimal.OVERHEAD;
                    result.msg_data = new Uint8Array(this.buffer.slice(BasicMinimal.HEADER_SIZE));
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(BasicMinimal.START_BYTE1);
        output.push(BasicMinimal.START_BYTE2);
        output.push(msg_id);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        const result = createFrameMsgInfo();

        if (buffer.length < BasicMinimal.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== BasicMinimal.START_BYTE1) {
            return result;
        }
        if (buffer[1] !== BasicMinimal.START_BYTE2) {
            return result;
        }

        const msg_length = buffer.length - BasicMinimal.OVERHEAD;

        result.valid = true;
        result.msg_id = buffer[2];
        result.msg_len = msg_length;
        result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, BasicMinimal.HEADER_SIZE));

        return result;
    }
}

module.exports = {
    BasicMinimal,
    BasicMinimalParserState,
};
