// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 18:04:46 2025.

const { createFrameMsgInfo, fletcher_checksum } = require('./frame_base');

// =============================================================================
// BasicExtendedMsgIds Frame Format
// =============================================================================

const BasicExtendedMsgIdsParserState = {
    LOOKING_FOR_START1: 0,
    LOOKING_FOR_START2: 1,
    GETTING_MSG_ID: 2,
    GETTING_LENGTH: 3,
    GETTING_PAYLOAD: 4
};

/**
 * BasicExtendedMsgIds - Frame format parser and encoder
 */
class BasicExtendedMsgIds {
    static START_BYTE1 = 0x90;
    static START_BYTE2 = 0x72;
    static HEADER_SIZE = 5;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 7;
    static LENGTH_BYTES = 1;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    reset() {
        this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicExtendedMsgIdsParserState.LOOKING_FOR_START1:
                if (byte === BasicExtendedMsgIds.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicExtendedMsgIdsParserState.LOOKING_FOR_START2:
                if (byte === BasicExtendedMsgIds.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicExtendedMsgIdsParserState.GETTING_MSG_ID;
                } else if (byte === BasicExtendedMsgIds.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicExtendedMsgIdsParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = BasicExtendedMsgIdsParserState.GETTING_LENGTH;
                break;

            case BasicExtendedMsgIdsParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                this.msg_length = byte;
                this.packet_size = BasicExtendedMsgIds.OVERHEAD + this.msg_length;
                this.state = BasicExtendedMsgIdsParserState.GETTING_PAYLOAD;
                break;

            case BasicExtendedMsgIdsParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    const msg_length = this.packet_size - BasicExtendedMsgIds.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 2, 2 + msg_length + 1 + 1);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(BasicExtendedMsgIds.HEADER_SIZE, this.packet_size - BasicExtendedMsgIds.FOOTER_SIZE));
                    }
                    this.state = BasicExtendedMsgIdsParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(BasicExtendedMsgIds.START_BYTE1);
        output.push(BasicExtendedMsgIds.START_BYTE2);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 2, 2 + msg.length + 1 + 1);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        const result = createFrameMsgInfo();

        if (buffer.length < BasicExtendedMsgIds.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== BasicExtendedMsgIds.START_BYTE1) {
            return result;
        }
        if (buffer[1] !== BasicExtendedMsgIds.START_BYTE2) {
            return result;
        }

        const msg_length = buffer.length - BasicExtendedMsgIds.OVERHEAD;

        const ck = fletcher_checksum(buffer, 2, 2 + msg_length + 1 + 1);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[2];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, BasicExtendedMsgIds.HEADER_SIZE, buffer.length - BasicExtendedMsgIds.FOOTER_SIZE));
        }

        return result;
    }
}

module.exports = {
    BasicExtendedMsgIds,
    BasicExtendedMsgIdsParserState,
};
