// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

const {
    createFrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
} = require('./frame_base');

// =============================================================================
// BasicMultiSystemStream Frame Format
// =============================================================================

const BasicMultiSystemStreamParserState = {
    LOOKING_FOR_START1: 0,
    LOOKING_FOR_START2: 1,
    GETTING_MSG_ID: 2,
    GETTING_LENGTH: 3,
    GETTING_PAYLOAD: 4
};

/**
 * BasicMultiSystemStream - Frame format parser and encoder
 */
class BasicMultiSystemStream {
    static START_BYTE1 = 0x90;
    static START_BYTE2 = 0x77;
    static HEADER_SIZE = 7;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 9;
    static LENGTH_BYTES = 1;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    reset() {
        this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicMultiSystemStreamParserState.LOOKING_FOR_START1:
                if (byte === BasicMultiSystemStream.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicMultiSystemStreamParserState.LOOKING_FOR_START2:
                if (byte === BasicMultiSystemStream.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicMultiSystemStreamParserState.GETTING_MSG_ID;
                } else if (byte === BasicMultiSystemStream.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicMultiSystemStreamParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = BasicMultiSystemStreamParserState.GETTING_LENGTH;
                break;

            case BasicMultiSystemStreamParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                this.msg_length = byte;
                this.packet_size = BasicMultiSystemStream.OVERHEAD + this.msg_length;
                this.state = BasicMultiSystemStreamParserState.GETTING_PAYLOAD;
                break;

            case BasicMultiSystemStreamParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Use shared payload validation with CRC
                    const validationResult = validate_payload_with_crc(this.buffer, BasicMultiSystemStream.HEADER_SIZE, 1, 2);
                    if (validationResult.valid) {
                        result.valid = validationResult.valid;
                        result.msg_id = validationResult.msg_id;
                        result.msg_len = validationResult.msg_len;
                        result.msg_data = validationResult.msg_data;
                    }
                    this.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(BasicMultiSystemStream.START_BYTE1);
        output.push(BasicMultiSystemStream.START_BYTE2);
        // Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 1, 2);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        if (buffer.length < BasicMultiSystemStream.OVERHEAD) {
            return createFrameMsgInfo();
        }

        if (buffer[0] !== BasicMultiSystemStream.START_BYTE1) {
            return createFrameMsgInfo();
        }
        if (buffer[1] !== BasicMultiSystemStream.START_BYTE2) {
            return createFrameMsgInfo();
        }

        // Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, BasicMultiSystemStream.HEADER_SIZE, 1, 2);
    }
}

module.exports = {
    BasicMultiSystemStream,
    BasicMultiSystemStreamParserState,
};
