// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 16:33:01 2025.

const { createFrameMsgInfo, fletcher_checksum } = require('./frame_base');

// =============================================================================
// BasicExtended Frame Format
// =============================================================================

const BasicExtendedParserState = {
    LOOKING_FOR_START1: 0,
    LOOKING_FOR_START2: 1,
    GETTING_MSG_ID: 2,
    GETTING_LENGTH: 3,
    GETTING_PAYLOAD: 4
};

/**
 * BasicExtended - Frame format parser and encoder
 */
class BasicExtended {
    static START_BYTE1 = 0x90;
    static START_BYTE2 = 0x74;
    static HEADER_SIZE = 6;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 8;
    static LENGTH_BYTES = 2;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = BasicExtendedParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    reset() {
        this.state = BasicExtendedParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicExtendedParserState.LOOKING_FOR_START1:
                if (byte === BasicExtended.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicExtendedParserState.LOOKING_FOR_START2:
                if (byte === BasicExtended.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicExtendedParserState.GETTING_MSG_ID;
                } else if (byte === BasicExtended.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicExtendedParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicExtendedParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = BasicExtendedParserState.GETTING_LENGTH;
                break;

            case BasicExtendedParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 4) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = BasicExtended.OVERHEAD + this.msg_length;
                    this.state = BasicExtendedParserState.GETTING_PAYLOAD;
                }
                break;

            case BasicExtendedParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    const msg_length = this.packet_size - BasicExtended.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 2, 2 + msg_length + 1 + 2);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(BasicExtended.HEADER_SIZE, this.packet_size - BasicExtended.FOOTER_SIZE));
                    }
                    this.state = BasicExtendedParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(BasicExtended.START_BYTE1);
        output.push(BasicExtended.START_BYTE2);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        output.push((msg.length >> 8) & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 2, 2 + msg.length + 1 + 2);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        const result = createFrameMsgInfo();

        if (buffer.length < BasicExtended.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== BasicExtended.START_BYTE1) {
            return result;
        }
        if (buffer[1] !== BasicExtended.START_BYTE2) {
            return result;
        }

        const msg_length = buffer.length - BasicExtended.OVERHEAD;

        const ck = fletcher_checksum(buffer, 2, 2 + msg_length + 1 + 2);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[2];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, BasicExtended.HEADER_SIZE, buffer.length - BasicExtended.FOOTER_SIZE));
        }

        return result;
    }
}

module.exports = {
    BasicExtended,
    BasicExtendedParserState,
};
