// Automatically generated frame parser package
// Generated by 0.0.1 at Fri Dec 19 18:24:29 2025.

// Base utilities
const frameBase = require('./frame_base');

// Frame headers
const frameHeadersBase = require('./frame_headers/base');
const headerTiny = require('./frame_headers/header_tiny');
const headerBasic = require('./frame_headers/header_basic');

// Payload types
const payloadTypesBase = require('./payload_types/base');
const payloadDefault = require('./payload_types/payload_default');
const payloadMinimal = require('./payload_types/payload_minimal');

// Frame format configuration
const frameFormatConfig = require('./FrameFormatConfig');

module.exports = {
    // Base utilities
    ...frameBase,
    // Frame headers
    ...frameHeadersBase,
    ...headerTiny,
    ...headerBasic,
    // Payload types
    ...payloadTypesBase,
    ...payloadDefault,
    ...payloadMinimal,
    // Frame format configuration
    ...frameFormatConfig,
};
