// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 19:40:48 2025.

const { createFrameMsgInfo, fletcher_checksum } = require('./frame_base');

// =============================================================================
// MavlinkV1Frame Frame Format
// =============================================================================

const MavlinkV1FrameParserState = {
    LOOKING_FOR_START: 0,
    GETTING_MSG_ID: 1,
    GETTING_LENGTH: 2,
    GETTING_PAYLOAD: 3
};

/**
 * MavlinkV1Frame - Frame format parser and encoder
 */
class MavlinkV1Frame {
    static START_BYTE = 0xFE;
    static HEADER_SIZE = 6;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 8;
    static LENGTH_BYTES = 1;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    reset() {
        this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case MavlinkV1FrameParserState.LOOKING_FOR_START:
                if (byte === MavlinkV1Frame.START_BYTE) {
                    this.buffer = [byte];
                    this.state = MavlinkV1FrameParserState.GETTING_MSG_ID;
                }
                break;

            case MavlinkV1FrameParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = MavlinkV1FrameParserState.GETTING_LENGTH;
                break;

            case MavlinkV1FrameParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                this.msg_length = byte;
                this.packet_size = MavlinkV1Frame.OVERHEAD + this.msg_length;
                this.state = MavlinkV1FrameParserState.GETTING_PAYLOAD;
                break;

            case MavlinkV1FrameParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    const msg_length = this.packet_size - MavlinkV1Frame.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 1, 1 + msg_length + 1 + 1);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(MavlinkV1Frame.HEADER_SIZE, this.packet_size - MavlinkV1Frame.FOOTER_SIZE));
                    }
                    this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(MavlinkV1Frame.START_BYTE);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 1, 1 + msg.length + 1 + 1);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        const result = createFrameMsgInfo();

        if (buffer.length < MavlinkV1Frame.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== MavlinkV1Frame.START_BYTE) {
            return result;
        }

        const msg_length = buffer.length - MavlinkV1Frame.OVERHEAD;

        const ck = fletcher_checksum(buffer, 1, 1 + msg_length + 1 + 1);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[1];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, MavlinkV1Frame.HEADER_SIZE, buffer.length - MavlinkV1Frame.FOOTER_SIZE));
        }

        return result;
    }
}

module.exports = {
    MavlinkV1Frame,
    MavlinkV1FrameParserState,
};
