// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

const {
    createFrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
} = require('./frame_base');

// =============================================================================
// MavlinkV1Frame Frame Format
// =============================================================================

const MavlinkV1FrameParserState = {
    LOOKING_FOR_START: 0,
    GETTING_MSG_ID: 1,
    GETTING_LENGTH: 2,
    GETTING_PAYLOAD: 3
};

/**
 * MavlinkV1Frame - Frame format parser and encoder
 */
class MavlinkV1Frame {
    static START_BYTE = 0xFE;
    static HEADER_SIZE = 6;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 8;
    static LENGTH_BYTES = 1;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    reset() {
        this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case MavlinkV1FrameParserState.LOOKING_FOR_START:
                if (byte === MavlinkV1Frame.START_BYTE) {
                    this.buffer = [byte];
                    this.state = MavlinkV1FrameParserState.GETTING_MSG_ID;
                }
                break;

            case MavlinkV1FrameParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = MavlinkV1FrameParserState.GETTING_LENGTH;
                break;

            case MavlinkV1FrameParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                this.msg_length = byte;
                this.packet_size = MavlinkV1Frame.OVERHEAD + this.msg_length;
                this.state = MavlinkV1FrameParserState.GETTING_PAYLOAD;
                break;

            case MavlinkV1FrameParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Use shared payload validation with CRC
                    const validationResult = validate_payload_with_crc(this.buffer, MavlinkV1Frame.HEADER_SIZE, 1, 1);
                    if (validationResult.valid) {
                        result.valid = validationResult.valid;
                        result.msg_id = validationResult.msg_id;
                        result.msg_len = validationResult.msg_len;
                        result.msg_data = validationResult.msg_data;
                    }
                    this.state = MavlinkV1FrameParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(MavlinkV1Frame.START_BYTE);
        // Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 1, 1);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        if (buffer.length < MavlinkV1Frame.OVERHEAD) {
            return createFrameMsgInfo();
        }

        if (buffer[0] !== MavlinkV1Frame.START_BYTE) {
            return createFrameMsgInfo();
        }

        // Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, MavlinkV1Frame.HEADER_SIZE, 1, 1);
    }
}

module.exports = {
    MavlinkV1Frame,
    MavlinkV1FrameParserState,
};
