// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 18:04:46 2025.

const { createFrameMsgInfo, fletcher_checksum } = require('./frame_base');

// =============================================================================
// TinyExtended Frame Format
// =============================================================================

const TinyExtendedParserState = {
    LOOKING_FOR_START: 0,
    GETTING_MSG_ID: 1,
    GETTING_LENGTH: 2,
    GETTING_PAYLOAD: 3
};

/**
 * TinyExtended - Frame format parser and encoder
 */
class TinyExtended {
    static START_BYTE = 0x74;
    static HEADER_SIZE = 5;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 7;
    static LENGTH_BYTES = 2;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = TinyExtendedParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    reset() {
        this.state = TinyExtendedParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case TinyExtendedParserState.LOOKING_FOR_START:
                if (byte === TinyExtended.START_BYTE) {
                    this.buffer = [byte];
                    this.state = TinyExtendedParserState.GETTING_MSG_ID;
                }
                break;

            case TinyExtendedParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = TinyExtendedParserState.GETTING_LENGTH;
                break;

            case TinyExtendedParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 3) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = TinyExtended.OVERHEAD + this.msg_length;
                    this.state = TinyExtendedParserState.GETTING_PAYLOAD;
                }
                break;

            case TinyExtendedParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    const msg_length = this.packet_size - TinyExtended.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 1, 1 + msg_length + 1 + 2);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(TinyExtended.HEADER_SIZE, this.packet_size - TinyExtended.FOOTER_SIZE));
                    }
                    this.state = TinyExtendedParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(TinyExtended.START_BYTE);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        output.push((msg.length >> 8) & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 1, 1 + msg.length + 1 + 2);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        const result = createFrameMsgInfo();

        if (buffer.length < TinyExtended.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== TinyExtended.START_BYTE) {
            return result;
        }

        const msg_length = buffer.length - TinyExtended.OVERHEAD;

        const ck = fletcher_checksum(buffer, 1, 1 + msg_length + 1 + 2);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[1];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, TinyExtended.HEADER_SIZE, buffer.length - TinyExtended.FOOTER_SIZE));
        }

        return result;
    }
}

module.exports = {
    TinyExtended,
    TinyExtendedParserState,
};
