// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

const {
    createFrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
} = require('./frame_base');

// =============================================================================
// TinyExtendedMultiSystemStream Frame Format
// =============================================================================

const TinyExtendedMultiSystemStreamParserState = {
    LOOKING_FOR_START: 0,
    GETTING_MSG_ID: 1,
    GETTING_LENGTH: 2,
    GETTING_PAYLOAD: 3
};

/**
 * TinyExtendedMultiSystemStream - Frame format parser and encoder
 */
class TinyExtendedMultiSystemStream {
    static START_BYTE = 0x78;
    static HEADER_SIZE = 8;
    static FOOTER_SIZE = 2;
    static OVERHEAD = 10;
    static LENGTH_BYTES = 2;

    constructor(get_msg_length) {
        this.get_msg_length = get_msg_length;
        this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    reset() {
        this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    parse_byte(byte) {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START:
                if (byte === TinyExtendedMultiSystemStream.START_BYTE) {
                    this.buffer = [byte];
                    this.state = TinyExtendedMultiSystemStreamParserState.GETTING_MSG_ID;
                }
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = TinyExtendedMultiSystemStreamParserState.GETTING_LENGTH;
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 3) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = TinyExtendedMultiSystemStream.OVERHEAD + this.msg_length;
                    this.state = TinyExtendedMultiSystemStreamParserState.GETTING_PAYLOAD;
                }
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Use shared payload validation with CRC
                    const validationResult = validate_payload_with_crc(this.buffer, TinyExtendedMultiSystemStream.HEADER_SIZE, 2, 1);
                    if (validationResult.valid) {
                        result.valid = validationResult.valid;
                        result.msg_id = validationResult.msg_id;
                        result.msg_len = validationResult.msg_len;
                        result.msg_data = validationResult.msg_data;
                    }
                    this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    static encode(msg_id, msg) {
        const output = [];
        output.push(TinyExtendedMultiSystemStream.START_BYTE);
        // Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 2, 1);
        return new Uint8Array(output);
    }

    static validate_packet(buffer) {
        if (buffer.length < TinyExtendedMultiSystemStream.OVERHEAD) {
            return createFrameMsgInfo();
        }

        if (buffer[0] !== TinyExtendedMultiSystemStream.START_BYTE) {
            return createFrameMsgInfo();
        }

        // Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, TinyExtendedMultiSystemStream.HEADER_SIZE, 2, 1);
    }
}

module.exports = {
    TinyExtendedMultiSystemStream,
    TinyExtendedMultiSystemStreamParserState,
};
