// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 19:40:48 2025.

import { FrameMsgInfo, createFrameMsgInfo, fletcher_checksum } from './frame_base';

// =============================================================================
// BasicExtendedLength Frame Format
// =============================================================================

export enum BasicExtendedLengthParserState {
    LOOKING_FOR_START1 = 0,
    LOOKING_FOR_START2 = 1,
    GETTING_MSG_ID = 2,
    GETTING_LENGTH = 3,
    GETTING_PAYLOAD = 4
}

/**
 * BasicExtendedLength - Frame format parser and encoder
 * 
 * Format: [START_BYTE1=0x90] [START_BYTE2=0x73] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]
 */
export class BasicExtendedLength {
    static readonly START_BYTE1 = 0x90;
    static readonly START_BYTE2 = 0x73;
    static readonly HEADER_SIZE = 5;
    static readonly FOOTER_SIZE = 2;
    static readonly OVERHEAD = 7;
    static readonly LENGTH_BYTES = 2;

    private state: BasicExtendedLengthParserState;
    private buffer: number[];
    private packet_size: number;
    private msg_id: number;
    private msg_length: number;
    private length_lo: number;
    private get_msg_length?: (msg_id: number) => number | undefined;

    /**
     * Create a new BasicExtendedLength parser
     * @param get_msg_length Callback to get message length from msg_id (required for non-length frames)
     */
    constructor(get_msg_length?: (msg_id: number) => number | undefined) {
        this.get_msg_length = get_msg_length;
        this.state = BasicExtendedLengthParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    /** Reset parser state */
    reset(): void {
        this.state = BasicExtendedLengthParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    /**
     * Parse a single byte
     * @param byte The byte to parse
     * @returns FrameMsgInfo with valid=true when a complete valid message is received
     */
    parse_byte(byte: number): FrameMsgInfo {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicExtendedLengthParserState.LOOKING_FOR_START1:
                if (byte === BasicExtendedLength.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedLengthParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicExtendedLengthParserState.LOOKING_FOR_START2:
                if (byte === BasicExtendedLength.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicExtendedLengthParserState.GETTING_MSG_ID;
                } else if (byte === BasicExtendedLength.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicExtendedLengthParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicExtendedLengthParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicExtendedLengthParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = BasicExtendedLengthParserState.GETTING_LENGTH;
                break;

            case BasicExtendedLengthParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 4) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = BasicExtendedLength.OVERHEAD + this.msg_length;
                    this.state = BasicExtendedLengthParserState.GETTING_PAYLOAD;
                }
                break;

            case BasicExtendedLengthParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Validate checksum
                    const msg_length = this.packet_size - BasicExtendedLength.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 2, 2 + msg_length + 1 + 2);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(BasicExtendedLength.HEADER_SIZE, this.packet_size - BasicExtendedLength.FOOTER_SIZE));
                    }
                    this.state = BasicExtendedLengthParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    /**
     * Encode a message with BasicExtendedLength format
     * @param msg_id Message ID
     * @param msg Message data
     * @returns Encoded frame as Uint8Array
     */
    static encode(msg_id: number, msg: Uint8Array | number[]): Uint8Array {
        const output: number[] = [];
        output.push(BasicExtendedLength.START_BYTE1);
        output.push(BasicExtendedLength.START_BYTE2);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        output.push((msg.length >> 8) & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 2, 2 + msg.length + 1 + 2);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    /**
     * Validate a complete BasicExtendedLength packet in a buffer
     * @param buffer Buffer containing the complete packet
     * @returns FrameMsgInfo with valid=true if packet is valid
     */
    static validate_packet(buffer: Uint8Array | number[]): FrameMsgInfo {
        const result = createFrameMsgInfo();

        if (buffer.length < BasicExtendedLength.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== BasicExtendedLength.START_BYTE1) {
            return result;
        }
        if (buffer[1] !== BasicExtendedLength.START_BYTE2) {
            return result;
        }

        const msg_length = buffer.length - BasicExtendedLength.OVERHEAD;

        // Validate checksum
        const ck = fletcher_checksum(buffer, 2, 2 + msg_length + 1 + 2);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[2];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, BasicExtendedLength.HEADER_SIZE, buffer.length - BasicExtendedLength.FOOTER_SIZE));
        }

        return result;
    }
}
