// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

import {
    FrameMsgInfo, createFrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
} from './frame_base';

// =============================================================================
// BasicMinimal Frame Format
// =============================================================================

export enum BasicMinimalParserState {
    LOOKING_FOR_START1 = 0,
    LOOKING_FOR_START2 = 1,
    GETTING_MSG_ID = 2,
    GETTING_PAYLOAD = 3
}

/**
 * BasicMinimal - Frame format parser and encoder
 * 
 * Format: [START_BYTE1=0x90] [START_BYTE2=0x70] [MSG_ID] [MSG...]
 */
export class BasicMinimal {
    static readonly START_BYTE1 = 0x90;
    static readonly START_BYTE2 = 0x70;
    static readonly HEADER_SIZE = 3;
    static readonly FOOTER_SIZE = 0;
    static readonly OVERHEAD = 3;

    private state: BasicMinimalParserState;
    private buffer: number[];
    private packet_size: number;
    private msg_id: number;
    private get_msg_length?: (msg_id: number) => number | undefined;

    /**
     * Create a new BasicMinimal parser
     * @param get_msg_length Callback to get message length from msg_id (required for non-length frames)
     */
    constructor(get_msg_length?: (msg_id: number) => number | undefined) {
        this.get_msg_length = get_msg_length;
        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
    }

    /** Reset parser state */
    reset(): void {
        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
    }

    /**
     * Parse a single byte
     * @param byte The byte to parse
     * @returns FrameMsgInfo with valid=true when a complete valid message is received
     */
    parse_byte(byte: number): FrameMsgInfo {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case BasicMinimalParserState.LOOKING_FOR_START1:
                if (byte === BasicMinimal.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMinimalParserState.LOOKING_FOR_START2;
                }
                break;

            case BasicMinimalParserState.LOOKING_FOR_START2:
                if (byte === BasicMinimal.START_BYTE2) {
                    this.buffer.push(byte);
                    this.state = BasicMinimalParserState.GETTING_MSG_ID;
                } else if (byte === BasicMinimal.START_BYTE1) {
                    this.buffer = [byte];
                    this.state = BasicMinimalParserState.LOOKING_FOR_START2;
                } else {
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicMinimalParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                if (this.get_msg_length) {
                    const msg_length = this.get_msg_length(byte);
                    if (msg_length !== undefined) {
                        this.packet_size = BasicMinimal.OVERHEAD + msg_length;
                        this.state = BasicMinimalParserState.GETTING_PAYLOAD;
                    } else {
                        this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                    }
                } else {
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;

            case BasicMinimalParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Use shared minimal payload validation
                    const validationResult = validate_payload_minimal(this.buffer, BasicMinimal.HEADER_SIZE);
                    result.valid = validationResult.valid;
                    result.msg_id = validationResult.msg_id;
                    result.msg_len = validationResult.msg_len;
                    result.msg_data = validationResult.msg_data;
                    this.state = BasicMinimalParserState.LOOKING_FOR_START1;
                }
                break;
        }

        return result;
    }

    /**
     * Encode a message with BasicMinimal format
     * @param msg_id Message ID
     * @param msg Message data
     * @returns Encoded frame as Uint8Array
     */
    static encode(msg_id: number, msg: Uint8Array | number[]): Uint8Array {
        const output: number[] = [];
        output.push(BasicMinimal.START_BYTE1);
        output.push(BasicMinimal.START_BYTE2);
        // Use shared minimal payload encoding
        encode_payload_minimal(output, msg_id, msg);
        return new Uint8Array(output);
    }

    /**
     * Validate a complete BasicMinimal packet in a buffer
     * @param buffer Buffer containing the complete packet
     * @returns FrameMsgInfo with valid=true if packet is valid
     */
    static validate_packet(buffer: Uint8Array | number[]): FrameMsgInfo {
        if (buffer.length < BasicMinimal.OVERHEAD) {
            return createFrameMsgInfo();
        }

        if (buffer[0] !== BasicMinimal.START_BYTE1) {
            return createFrameMsgInfo();
        }
        if (buffer[1] !== BasicMinimal.START_BYTE2) {
            return createFrameMsgInfo();
        }

        // Use shared minimal payload validation
        return validate_payload_minimal(buffer, BasicMinimal.HEADER_SIZE);
    }
}
