// Automatically generated frame parser package
// Generated by 0.0.1 at Fri Dec 19 18:24:29 2025.

// Base utilities and generic parser infrastructure
export {
    FrameFormatType,
    FrameMsgInfo,
    createFrameMsgInfo,
    fletcher_checksum,
    // Configuration interface for code reuse
    FrameParserConfig,
    // Generic parser class (use createFrameParserClass for type-safe wrappers)
    GenericFrameParser,
    GenericParserState,
    createFrameParserClass,
    // Shared payload parsing functions
    validate_payload_with_crc,
    validate_payload_minimal,
    encode_payload_with_crc,
    encode_payload_minimal,
} from './frame_base';

// Frame headers - Start byte patterns and header types
export {
    HeaderType,
    HeaderConfig,
    BASIC_START_BYTE,
    PAYLOAD_TYPE_BASE,
    UBX_SYNC1,
    UBX_SYNC2,
    MAVLINK_V1_STX,
    MAVLINK_V2_STX,
    MAX_PAYLOAD_TYPE,
    HEADER_NONE_CONFIG,
    HEADER_TINY_CONFIG,
    HEADER_BASIC_CONFIG,
    HEADER_UBX_CONFIG,
    HEADER_MAVLINK_V1_CONFIG,
    HEADER_MAVLINK_V2_CONFIG,
} from './frame_headers';

// Payload types - Message structure definitions
export {
    PayloadType,
    MAX_PAYLOAD_TYPE_VALUE,
    PayloadConfig,
    payloadHeaderSize,
    payloadFooterSize,
    payloadOverhead,
    payloadMaxPayload,
    PAYLOAD_MINIMAL_CONFIG,
    PAYLOAD_DEFAULT_CONFIG,
    PAYLOAD_EXTENDED_MSG_IDS_CONFIG,
    PAYLOAD_EXTENDED_LENGTH_CONFIG,
    PAYLOAD_EXTENDED_CONFIG,
    PAYLOAD_SYS_COMP_CONFIG,
    PAYLOAD_SEQ_CONFIG,
    PAYLOAD_MULTI_SYSTEM_STREAM_CONFIG,
    PAYLOAD_EXTENDED_MULTI_SYSTEM_STREAM_CONFIG,
} from './payload_types';

// Frame profiles - Pre-defined Header + Payload combinations
export {
    // Profile configuration interface
    FrameProfileConfig,
    EncodeOptions,
    // Profile helper functions
    profileHeaderSize,
    profileFooterSize,
    profileOverhead,
    // Profile configurations
    ProfileStandardConfig,
    ProfileSensorConfig,
    ProfileIPCConfig,
    ProfileBulkConfig,
    ProfileNetworkConfig,
    // Generic encode/parse functions
    encodeFrameWithCrc,
    encodeFrameMinimal,
    parseFrameWithCrc,
    parseFrameMinimal,
    // BufferReader/BufferWriter/AccumulatingReader base classes
    BufferReader,
    BufferWriter,
    AccumulatingReader,
    AccumulatingReaderState,
    // Profile-specific subclasses
    ProfileStandardReader,
    ProfileStandardWriter,
    ProfileStandardAccumulatingReader,
    ProfileSensorReader,
    ProfileSensorWriter,
    ProfileSensorAccumulatingReader,
    ProfileIPCReader,
    ProfileIPCWriter,
    ProfileIPCAccumulatingReader,
    ProfileBulkReader,
    ProfileBulkWriter,
    ProfileBulkAccumulatingReader,
    ProfileNetworkReader,
    ProfileNetworkWriter,
    ProfileNetworkAccumulatingReader,
} from './frame_profiles';

