// Automatically generated frame parser package
// Generated by 0.0.1 at Fri Dec 19 18:24:29 2025.

// Base utilities and generic parser infrastructure
export {
    FrameFormatType,
    FrameMsgInfo,
    createFrameMsgInfo,
    fletcher_checksum,
    // Configuration interface for code reuse
    FrameParserConfig,
    // Generic parser class (use createFrameParserClass for type-safe wrappers)
    GenericFrameParser,
    GenericParserState,
    createFrameParserClass,
    // Shared payload parsing functions
    validate_payload_with_crc,
    validate_payload_minimal,
    encode_payload_with_crc,
    encode_payload_minimal,
} from './frame_base';

// Frame headers - Start byte patterns and header types
export { HeaderType, HeaderConfig, BASIC_START_BYTE, PAYLOAD_TYPE_BASE, UBX_SYNC1, UBX_SYNC2, MAVLINK_V1_STX, MAVLINK_V2_STX, MAX_PAYLOAD_TYPE } from './frame_headers/base';
export { HEADER_TINY_CONFIG, getTinyStartByte, isTinyStartByte, getPayloadTypeFromTiny } from './frame_headers/header_tiny';
export { HEADER_BASIC_CONFIG, getBasicSecondStartByte, isBasicSecondStartByte, getPayloadTypeFromBasic } from './frame_headers/header_basic';
export { HEADER_NONE_CONFIG } from './frame_headers/header_none';

// Payload types - Message structure definitions
export { PayloadType, MAX_PAYLOAD_TYPE_VALUE, PayloadConfig, payloadConfigHeaderSize, payloadConfigFooterSize, payloadConfigOverhead } from './payload_types/base';
export { PAYLOAD_DEFAULT_CONFIG } from './payload_types/payload_default';
export { PAYLOAD_MINIMAL_CONFIG } from './payload_types/payload_minimal';

// Frame format configuration
export { FrameFormatConfig, FrameFormatConfigConfig, FrameFormatConfigParserState } from './FrameFormatConfig';

// Frame profiles - Pre-defined Header + Payload combinations
export {
    // Profile configuration interface
    FrameProfileConfig,
    EncodeOptions,
    // Profile configurations
    ProfileStandardConfig,
    ProfileSensorConfig,
    ProfileIPCConfig,
    ProfileBulkConfig,
    ProfileNetworkConfig,
    // Generic encode/parse functions
    encodeFrameWithCrc,
    encodeFrameMinimal,
    parseFrameWithCrc,
    parseFrameMinimal,
    // Profile-specific convenience functions
    encodeProfileStandard,
    parseProfileStandardBuffer,
    encodeProfileSensor,
    parseProfileSensorBuffer,
    encodeProfileIPC,
    parseProfileIPCBuffer,
    encodeProfileBulk,
    parseProfileBulkBuffer,
    encodeProfileNetwork,
    parseProfileNetworkBuffer,
    // Profile parser interface
    ProfileParser,
    createProfileParserClass,
    ProfileStandard,
    ProfileSensor,
    ProfileIPC,
    ProfileBulk,
    ProfileNetwork,
    // BufferReader/BufferWriter/AccumulatingReader classes
    BufferReader,
    BufferWriter,
    AccumulatingReader,
    AccumulatingReaderState,
    // Convenience factory functions for profiles
    createProfileStandardReader,
    createProfileStandardWriter,
    createProfileStandardAccumulatingReader,
    createProfileSensorReader,
    createProfileSensorWriter,
    createProfileSensorAccumulatingReader,
    createProfileIPCReader,
    createProfileIPCWriter,
    createProfileIPCAccumulatingReader,
    createProfileBulkReader,
    createProfileBulkWriter,
    createProfileBulkAccumulatingReader,
    createProfileNetworkReader,
    createProfileNetworkWriter,
    createProfileNetworkAccumulatingReader,
} from './frame_profiles';
