// Automatically generated frame parser
// Generated by 0.0.1 at Wed Dec  3 17:57:16 2025.

import { FrameMsgInfo, createFrameMsgInfo, fletcher_checksum } from './frame_base';

// =============================================================================
// MavlinkV2Frame Frame Format
// =============================================================================

export enum MavlinkV2FrameParserState {
    LOOKING_FOR_START = 0,
    GETTING_MSG_ID = 1,
    GETTING_LENGTH = 2,
    GETTING_PAYLOAD = 3
}

/**
 * MavlinkV2Frame - Frame format parser and encoder
 * 
 * Format: [STX=0xFD] [MSG_ID] [LEN] [MSG...] [CRC1] [CRC2]
 */
export class MavlinkV2Frame {
    static readonly START_BYTE = 0xFD;
    static readonly HEADER_SIZE = 5;
    static readonly FOOTER_SIZE = 2;
    static readonly OVERHEAD = 7;
    static readonly LENGTH_BYTES = 1;

    private state: MavlinkV2FrameParserState;
    private buffer: number[];
    private packet_size: number;
    private msg_id: number;
    private msg_length: number;
    private get_msg_length?: (msg_id: number) => number | undefined;

    /**
     * Create a new MavlinkV2Frame parser
     * @param get_msg_length Callback to get message length from msg_id (required for non-length frames)
     */
    constructor(get_msg_length?: (msg_id: number) => number | undefined) {
        this.get_msg_length = get_msg_length;
        this.state = MavlinkV2FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    /** Reset parser state */
    reset(): void {
        this.state = MavlinkV2FrameParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    /**
     * Parse a single byte
     * @param byte The byte to parse
     * @returns FrameMsgInfo with valid=true when a complete valid message is received
     */
    parse_byte(byte: number): FrameMsgInfo {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case MavlinkV2FrameParserState.LOOKING_FOR_START:
                if (byte === MavlinkV2Frame.START_BYTE) {
                    this.buffer = [byte];
                    this.state = MavlinkV2FrameParserState.GETTING_MSG_ID;
                }
                break;

            case MavlinkV2FrameParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = MavlinkV2FrameParserState.GETTING_LENGTH;
                break;

            case MavlinkV2FrameParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                this.msg_length = byte;
                this.packet_size = MavlinkV2Frame.OVERHEAD + this.msg_length;
                this.state = MavlinkV2FrameParserState.GETTING_PAYLOAD;
                break;

            case MavlinkV2FrameParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Validate checksum
                    const msg_length = this.packet_size - MavlinkV2Frame.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 1, 1 + msg_length + 1 + 1);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(MavlinkV2Frame.HEADER_SIZE, this.packet_size - MavlinkV2Frame.FOOTER_SIZE));
                    }
                    this.state = MavlinkV2FrameParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    /**
     * Encode a message with MavlinkV2Frame format
     * @param msg_id Message ID
     * @param msg Message data
     * @returns Encoded frame as Uint8Array
     */
    static encode(msg_id: number, msg: Uint8Array | number[]): Uint8Array {
        const output: number[] = [];
        output.push(MavlinkV2Frame.START_BYTE);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 1, 1 + msg.length + 1 + 1);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    /**
     * Validate a complete MavlinkV2Frame packet in a buffer
     * @param buffer Buffer containing the complete packet
     * @returns FrameMsgInfo with valid=true if packet is valid
     */
    static validate_packet(buffer: Uint8Array | number[]): FrameMsgInfo {
        const result = createFrameMsgInfo();

        if (buffer.length < MavlinkV2Frame.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== MavlinkV2Frame.START_BYTE) {
            return result;
        }

        const msg_length = buffer.length - MavlinkV2Frame.OVERHEAD;

        // Validate checksum
        const ck = fletcher_checksum(buffer, 1, 1 + msg_length + 1 + 1);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[1];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, MavlinkV2Frame.HEADER_SIZE, buffer.length - MavlinkV2Frame.FOOTER_SIZE));
        }

        return result;
    }
}
