// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

import {
    FrameMsgInfo, createFrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
} from './frame_base';

// =============================================================================
// TinyExtendedMultiSystemStream Frame Format
// =============================================================================

export enum TinyExtendedMultiSystemStreamParserState {
    LOOKING_FOR_START = 0,
    GETTING_MSG_ID = 1,
    GETTING_LENGTH = 2,
    GETTING_PAYLOAD = 3
}

/**
 * TinyExtendedMultiSystemStream - Frame format parser and encoder
 * 
 * Format: [START_BYTE=0x78] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]
 */
export class TinyExtendedMultiSystemStream {
    static readonly START_BYTE = 0x78;
    static readonly HEADER_SIZE = 8;
    static readonly FOOTER_SIZE = 2;
    static readonly OVERHEAD = 10;
    static readonly LENGTH_BYTES = 2;

    private state: TinyExtendedMultiSystemStreamParserState;
    private buffer: number[];
    private packet_size: number;
    private msg_id: number;
    private msg_length: number;
    private length_lo: number;
    private get_msg_length?: (msg_id: number) => number | undefined;

    /**
     * Create a new TinyExtendedMultiSystemStream parser
     * @param get_msg_length Callback to get message length from msg_id (required for non-length frames)
     */
    constructor(get_msg_length?: (msg_id: number) => number | undefined) {
        this.get_msg_length = get_msg_length;
        this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    /** Reset parser state */
    reset(): void {
        this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    /**
     * Parse a single byte
     * @param byte The byte to parse
     * @returns FrameMsgInfo with valid=true when a complete valid message is received
     */
    parse_byte(byte: number): FrameMsgInfo {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START:
                if (byte === TinyExtendedMultiSystemStream.START_BYTE) {
                    this.buffer = [byte];
                    this.state = TinyExtendedMultiSystemStreamParserState.GETTING_MSG_ID;
                }
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = TinyExtendedMultiSystemStreamParserState.GETTING_LENGTH;
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 3) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = TinyExtendedMultiSystemStream.OVERHEAD + this.msg_length;
                    this.state = TinyExtendedMultiSystemStreamParserState.GETTING_PAYLOAD;
                }
                break;

            case TinyExtendedMultiSystemStreamParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Use shared payload validation with CRC
                    const validationResult = validate_payload_with_crc(this.buffer, TinyExtendedMultiSystemStream.HEADER_SIZE, 2, 1);
                    if (validationResult.valid) {
                        result.valid = validationResult.valid;
                        result.msg_id = validationResult.msg_id;
                        result.msg_len = validationResult.msg_len;
                        result.msg_data = validationResult.msg_data;
                    }
                    this.state = TinyExtendedMultiSystemStreamParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    /**
     * Encode a message with TinyExtendedMultiSystemStream format
     * @param msg_id Message ID
     * @param msg Message data
     * @returns Encoded frame as Uint8Array
     */
    static encode(msg_id: number, msg: Uint8Array | number[]): Uint8Array {
        const output: number[] = [];
        output.push(TinyExtendedMultiSystemStream.START_BYTE);
        // Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 2, 1);
        return new Uint8Array(output);
    }

    /**
     * Validate a complete TinyExtendedMultiSystemStream packet in a buffer
     * @param buffer Buffer containing the complete packet
     * @returns FrameMsgInfo with valid=true if packet is valid
     */
    static validate_packet(buffer: Uint8Array | number[]): FrameMsgInfo {
        if (buffer.length < TinyExtendedMultiSystemStream.OVERHEAD) {
            return createFrameMsgInfo();
        }

        if (buffer[0] !== TinyExtendedMultiSystemStream.START_BYTE) {
            return createFrameMsgInfo();
        }

        // Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, TinyExtendedMultiSystemStream.HEADER_SIZE, 2, 1);
    }
}
