// Automatically generated frame parser
// Generated by 0.0.1 at Thu Dec  4 16:33:01 2025.

import { FrameMsgInfo, createFrameMsgInfo, fletcher_checksum } from './frame_base';

// =============================================================================
// TinyExtended Frame Format
// =============================================================================

export enum TinyExtendedParserState {
    LOOKING_FOR_START = 0,
    GETTING_MSG_ID = 1,
    GETTING_LENGTH = 2,
    GETTING_PAYLOAD = 3
}

/**
 * TinyExtended - Frame format parser and encoder
 * 
 * Format: [START_BYTE=0x74] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]
 */
export class TinyExtended {
    static readonly START_BYTE = 0x74;
    static readonly HEADER_SIZE = 5;
    static readonly FOOTER_SIZE = 2;
    static readonly OVERHEAD = 7;
    static readonly LENGTH_BYTES = 2;

    private state: TinyExtendedParserState;
    private buffer: number[];
    private packet_size: number;
    private msg_id: number;
    private msg_length: number;
    private length_lo: number;
    private get_msg_length?: (msg_id: number) => number | undefined;

    /**
     * Create a new TinyExtended parser
     * @param get_msg_length Callback to get message length from msg_id (required for non-length frames)
     */
    constructor(get_msg_length?: (msg_id: number) => number | undefined) {
        this.get_msg_length = get_msg_length;
        this.state = TinyExtendedParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
        this.length_lo = 0;
    }

    /** Reset parser state */
    reset(): void {
        this.state = TinyExtendedParserState.LOOKING_FOR_START;
        this.buffer = [];
        this.packet_size = 0;
        this.msg_id = 0;
        this.msg_length = 0;
    }

    /**
     * Parse a single byte
     * @param byte The byte to parse
     * @returns FrameMsgInfo with valid=true when a complete valid message is received
     */
    parse_byte(byte: number): FrameMsgInfo {
        const result = createFrameMsgInfo();

        switch (this.state) {
            case TinyExtendedParserState.LOOKING_FOR_START:
                if (byte === TinyExtended.START_BYTE) {
                    this.buffer = [byte];
                    this.state = TinyExtendedParserState.GETTING_MSG_ID;
                }
                break;

            case TinyExtendedParserState.GETTING_MSG_ID:
                this.buffer.push(byte);
                this.msg_id = byte;
                this.state = TinyExtendedParserState.GETTING_LENGTH;
                break;

            case TinyExtendedParserState.GETTING_LENGTH:
                this.buffer.push(byte);
                if (this.buffer.length === 3) {
                    this.length_lo = byte;
                } else {
                    this.msg_length = this.length_lo | (byte << 8);
                    this.packet_size = TinyExtended.OVERHEAD + this.msg_length;
                    this.state = TinyExtendedParserState.GETTING_PAYLOAD;
                }
                break;

            case TinyExtendedParserState.GETTING_PAYLOAD:
                this.buffer.push(byte);

                if (this.buffer.length >= this.packet_size) {
                    // Validate checksum
                    const msg_length = this.packet_size - TinyExtended.OVERHEAD;
                    const ck = fletcher_checksum(this.buffer, 1, 1 + msg_length + 1 + 2);
                    if (ck[0] === this.buffer[this.buffer.length - 2] && ck[1] === this.buffer[this.buffer.length - 1]) {
                        result.valid = true;
                        result.msg_id = this.msg_id;
                        result.msg_len = msg_length;
                        result.msg_data = new Uint8Array(this.buffer.slice(TinyExtended.HEADER_SIZE, this.packet_size - TinyExtended.FOOTER_SIZE));
                    }
                    this.state = TinyExtendedParserState.LOOKING_FOR_START;
                }
                break;
        }

        return result;
    }

    /**
     * Encode a message with TinyExtended format
     * @param msg_id Message ID
     * @param msg Message data
     * @returns Encoded frame as Uint8Array
     */
    static encode(msg_id: number, msg: Uint8Array | number[]): Uint8Array {
        const output: number[] = [];
        output.push(TinyExtended.START_BYTE);
        output.push(msg_id);
        output.push(msg.length & 0xFF);
        output.push((msg.length >> 8) & 0xFF);
        for (let i = 0; i < msg.length; i++) {
            output.push(msg[i]);
        }
        const ck = fletcher_checksum(output, 1, 1 + msg.length + 1 + 2);
        output.push(ck[0]);
        output.push(ck[1]);
        return new Uint8Array(output);
    }

    /**
     * Validate a complete TinyExtended packet in a buffer
     * @param buffer Buffer containing the complete packet
     * @returns FrameMsgInfo with valid=true if packet is valid
     */
    static validate_packet(buffer: Uint8Array | number[]): FrameMsgInfo {
        const result = createFrameMsgInfo();

        if (buffer.length < TinyExtended.OVERHEAD) {
            return result;
        }

        if (buffer[0] !== TinyExtended.START_BYTE) {
            return result;
        }

        const msg_length = buffer.length - TinyExtended.OVERHEAD;

        // Validate checksum
        const ck = fletcher_checksum(buffer, 1, 1 + msg_length + 1 + 2);
        if (ck[0] === buffer[buffer.length - 2] && ck[1] === buffer[buffer.length - 1]) {
            result.valid = true;
            result.msg_id = buffer[1];
            result.msg_len = msg_length;
            result.msg_data = new Uint8Array(Array.prototype.slice.call(buffer, TinyExtended.HEADER_SIZE, buffer.length - TinyExtended.FOOTER_SIZE));
        }

        return result;
    }
}
