/* Automatically generated frame parser base utilities */
/* Generated by 0.0.1 at Thu Dec  4 18:04:46 2025. */

#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <functional>

namespace FrameParsers {

// Frame format type enumeration
enum class FrameFormatType {
    TINY_MINIMAL = 0,
    TINY_DEFAULT = 1,
    TINY_EXTENDED_MSG_IDS = 2,
    TINY_EXTENDED_LENGTH = 3,
    TINY_EXTENDED = 4,
    TINY_SYS_COMP = 5,
    TINY_SEQ = 6,
    TINY_MULTI_SYSTEM_STREAM = 7,
    TINY_EXTENDED_MULTI_SYSTEM_STREAM = 8,
    BASIC_MINIMAL = 9,
    BASIC_DEFAULT = 10,
    BASIC_EXTENDED_MSG_IDS = 11,
    BASIC_EXTENDED_LENGTH = 12,
    BASIC_EXTENDED = 13,
    BASIC_SYS_COMP = 14,
    BASIC_SEQ = 15,
    BASIC_MULTI_SYSTEM_STREAM = 16,
    BASIC_EXTENDED_MULTI_SYSTEM_STREAM = 17,
    UBX_FRAME = 18,
    MAVLINK_V1_FRAME = 19,
    MAVLINK_V2_FRAME = 20,
    FRAME_FORMAT_CONFIG = 21,
};

// Checksum result
struct FrameChecksum {
    uint8_t byte1;
    uint8_t byte2;
};

// Fletcher-16 checksum calculation
inline FrameChecksum fletcher_checksum(const uint8_t* data, size_t length) {
    FrameChecksum ck{0, 0};
    for (size_t i = 0; i < length; i++) {
        ck.byte1 = static_cast<uint8_t>(ck.byte1 + data[i]);
        ck.byte2 = static_cast<uint8_t>(ck.byte2 + ck.byte1);
    }
    return ck;
}

// Parse result
struct FrameMsgInfo {
    bool valid;
    uint8_t msg_id;
    size_t msg_len;
    uint8_t* msg_data;

    FrameMsgInfo() : valid(false), msg_id(0), msg_len(0), msg_data(nullptr) {}
    FrameMsgInfo(bool v, uint8_t id, size_t len, uint8_t* data)
        : valid(v), msg_id(id), msg_len(len), msg_data(data) {}
};

}  // namespace FrameParsers
