/* Automatically generated frame parser main header */
/* Generated by 0.0.1 at Fri Dec 19 18:24:29 2025. */

#pragma once

/* Base utilities */
#include "frame_base.hpp"

/* Individual frame format parsers */
#include "TinyMinimal.hpp"
#include "TinyDefault.hpp"
#include "TinyExtendedMsgIds.hpp"
#include "TinyExtendedLength.hpp"
#include "TinyExtended.hpp"
#include "TinySysComp.hpp"
#include "TinySeq.hpp"
#include "TinyMultiSystemStream.hpp"
#include "TinyExtendedMultiSystemStream.hpp"
#include "BasicMinimal.hpp"
#include "BasicDefault.hpp"
#include "BasicExtendedMsgIds.hpp"
#include "BasicExtendedLength.hpp"
#include "BasicExtended.hpp"
#include "BasicSysComp.hpp"
#include "BasicSeq.hpp"
#include "BasicMultiSystemStream.hpp"
#include "BasicExtendedMultiSystemStream.hpp"
#include "UbxFrame.hpp"
#include "MavlinkV1Frame.hpp"
#include "MavlinkV2Frame.hpp"
#include "FrameFormatConfig.hpp"

/* Frame Profile Aliases */
namespace FrameParsers {

// Standard profile aliases for common use cases
using ProfileStandard = BasicDefaultParser;  // General Serial / UART
using ProfileSensor = TinyMinimalParser;     // Low-Bandwidth / Radio
// using ProfileIPC = NoneMinimalParser;        // Trusted / Board-to-Board (NoneMinimal not generated for C++)
using ProfileBulk = BasicExtendedParser;     // Firmware / File Transfer
using ProfileNetwork = BasicExtendedMultiSystemStreamParser;  // Multi-Node Mesh / Swarm

}  // namespace FrameParsers
