#!/usr/bin/env python3
# kate: replace-tabs on; indent-width 4;

"""
Python Frame Parser Generator

Generates Python code for frame parsers based on frame format definitions.
"""

from struct_frame import version
import time


def camel_to_snake(name):
    """Convert CamelCase to snake_case"""
    import re
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    name = re.sub('([a-z0-9])([A-Z])', r'\1_\2', name)
    return name.lower()


def camel_to_upper_snake(name):
    """Convert CamelCase to UPPER_SNAKE_CASE"""
    return camel_to_snake(name).upper()


class FrameParserPyGen:
    """Generates Python code for frame parsers"""

    @staticmethod
    def generate_base(formats):
        """Generate the base Python file with common utilities"""
        yield '# Automatically generated frame parser base utilities\n'
        yield f'# Generated by {version} at {time.asctime()}.\n\n'
        yield 'from enum import Enum\n'
        yield 'from typing import List, Tuple, Union\n'
        yield 'from dataclasses import dataclass\n\n'

        # Generate frame format enum
        yield '# Frame format type enumeration\n'
        yield 'class FrameFormatType(Enum):\n'
        for i, fmt in enumerate(formats):
            enum_name = camel_to_upper_snake(fmt.name)
            yield f'    {enum_name} = {i}\n'
        yield '\n\n'

        # Generate checksum function
        yield '''def fletcher_checksum(buffer: Union[bytes, List[int]], start: int = 0, end: int = None) -> Tuple[int, int]:
    """Calculate Fletcher-16 checksum over the given data"""
    if end is None:
        end = len(buffer)

    byte1 = 0
    byte2 = 0

    for x in range(start, end):
        byte1 = (byte1 + buffer[x]) % 256
        byte2 = (byte2 + byte1) % 256

    return (byte1, byte2)


'''

        # Generate common result class
        yield '''@dataclass
class FrameMsgInfo:
    """Parse result containing message information"""
    valid: bool = False
    msg_id: int = 0
    msg_len: int = 0
    msg_data: bytes = b\'\'
'''

    @staticmethod
    def generate_format_file(fmt):
        """Generate a Python file for a single frame format"""
        yield '# Automatically generated frame parser\n'
        yield f'# Generated by {version} at {time.asctime()}.\n\n'
        yield 'from enum import Enum\n'
        yield 'from typing import Callable, List, Union\n'
        yield 'from .frame_base import FrameMsgInfo, fletcher_checksum\n\n'

        yield from FrameParserPyGen.generate_format(fmt)

    @staticmethod
    def generate_init(formats):
        """Generate __init__.py that exports all frame formats"""
        yield '# Automatically generated frame parser package\n'
        yield f'# Generated by {version} at {time.asctime()}.\n\n'
        yield '# Base utilities\n'
        yield 'from .frame_base import (\n'
        yield '    FrameFormatType,\n'
        yield '    FrameMsgInfo,\n'
        yield '    fletcher_checksum,\n'
        yield ')\n\n'

        yield '# Individual frame format parsers\n'
        for fmt in formats:
            snake_name = camel_to_snake(fmt.name)
            yield f'from .{snake_name} import {fmt.name}, {fmt.name}ParserState\n'

        yield '\n# Re-export all frame formats\n'
        yield '__all__ = [\n'
        yield '    # Base utilities\n'
        yield '    "FrameFormatType",\n'
        yield '    "FrameMsgInfo",\n'
        yield '    "fletcher_checksum",\n'
        yield '    # Frame formats\n'
        for fmt in formats:
            yield f'    "{fmt.name}",\n'
            yield f'    "{fmt.name}ParserState",\n'
        yield ']\n'

    @staticmethod
    def generate(formats):
        """Generate the complete frame parser Python file (single file, legacy mode)"""
        yield '# Automatically generated frame parser\n'
        yield f'# Generated by {version} at {time.asctime()}.\n\n'
        yield 'from enum import Enum\n'
        yield 'from typing import Optional, Callable, Dict, List, Tuple, Union\n'
        yield 'from dataclasses import dataclass\n\n'
        
        # Generate frame format enum
        yield '# Frame format type enumeration\n'
        yield 'class FrameFormatType(Enum):\n'
        for i, fmt in enumerate(formats):
            enum_name = camel_to_upper_snake(fmt.name)
            yield f'    {enum_name} = {i}\n'
        yield '\n\n'
        
        # Generate checksum function
        yield '''def fletcher_checksum(buffer: Union[bytes, List[int]], start: int = 0, end: int = None) -> Tuple[int, int]:
    """Calculate Fletcher-16 checksum over the given data"""
    if end is None:
        end = len(buffer)
    
    byte1 = 0
    byte2 = 0
    
    for x in range(start, end):
        byte1 = (byte1 + buffer[x]) % 256
        byte2 = (byte2 + byte1) % 256
    
    return (byte1, byte2)


'''
        
        # Generate common result class
        yield '''@dataclass
class FrameMsgInfo:
    """Parse result containing message information"""
    valid: bool = False
    msg_id: int = 0
    msg_len: int = 0
    msg_data: bytes = b''


'''
        
        # Generate individual frame format classes
        for fmt in formats:
            yield from FrameParserPyGen.generate_format(fmt)
            yield '\n\n'
            
    @staticmethod
    def generate_format(fmt):
        """Generate Python code for a single frame format"""
        name = fmt.name
        class_name = name
        prefix = camel_to_snake(name)
        PREFIX = camel_to_upper_snake(name)
        
        yield f'# =============================================================================\n'
        yield f'# {name} Frame Format\n'
        yield f'# =============================================================================\n\n'
        
        # Generate parser state enum
        yield f'class {class_name}ParserState(Enum):\n'
        state_idx = 0
        if fmt.start_bytes:
            for i in range(len(fmt.start_bytes)):
                state_name = f'LOOKING_FOR_START{i + 1}' if len(fmt.start_bytes) > 1 else 'LOOKING_FOR_START'
                yield f'    {state_name} = {state_idx}\n'
                state_idx += 1
        yield f'    GETTING_MSG_ID = {state_idx}\n'
        state_idx += 1
        if fmt.has_length:
            yield f'    GETTING_LENGTH = {state_idx}\n'
            state_idx += 1
        yield f'    GETTING_PAYLOAD = {state_idx}\n\n\n'
        
        # Generate frame format class
        yield f'class {class_name}:\n'
        yield f'    """\n'
        yield f'    {name} - Frame format parser and encoder\n'
        yield f'    \n'
        yield f'    Format: '
        parts = []
        for sb_name, sb_value in fmt.start_bytes:
            parts.append(f'[{sb_name.upper()}=0x{sb_value:02X}]')
        parts.append('[MSG_ID]')
        if fmt.has_length:
            parts.append(f'[LEN{"16" if fmt.length_bytes == 2 else ""}]')
        parts.append('[MSG...]')
        if fmt.has_crc:
            parts.append('[CRC1] [CRC2]')
        yield ' '.join(parts)
        yield '\n    """\n\n'
        
        # Constants
        for i, (sb_name, sb_value) in enumerate(fmt.start_bytes):
            const_name = f'START_BYTE{i + 1}' if len(fmt.start_bytes) > 1 else 'START_BYTE'
            yield f'    {const_name} = 0x{sb_value:02X}\n'
        yield f'    HEADER_SIZE = {fmt.header_size}\n'
        yield f'    FOOTER_SIZE = {fmt.footer_size}\n'
        yield f'    OVERHEAD = {fmt.header_size + fmt.footer_size}\n'
        if fmt.has_length:
            yield f'    LENGTH_BYTES = {fmt.length_bytes}\n'
        yield '\n'
        
        # __init__
        yield f'    def __init__(self, get_msg_length: Callable[[int], int] = None):\n'
        yield f'        """\n'
        yield f'        Initialize the {name} parser\n'
        yield f'        \n'
        yield f'        Args:\n'
        yield f'            get_msg_length: Callback function to get message length from msg_id\n'
        yield f'                            Required for formats without a length field\n'
        yield f'        """\n'
        yield f'        self.get_msg_length = get_msg_length\n'
        yield f'        self.reset()\n\n'
        
        # reset method
        yield f'    def reset(self):\n'
        yield f'        """Reset parser state"""\n'
        if fmt.start_bytes:
            state_name = 'LOOKING_FOR_START1' if len(fmt.start_bytes) > 1 else 'LOOKING_FOR_START'
            yield f'        self.state = {class_name}ParserState.{state_name}\n'
        else:
            yield f'        self.state = {class_name}ParserState.GETTING_MSG_ID\n'
        yield f'        self.buffer = []\n'
        yield f'        self.packet_size = 0\n'
        yield f'        self.msg_id = 0\n'
        if fmt.has_length:
            yield f'        self.msg_length = 0\n'
            if fmt.length_bytes == 2:
                yield f'        self.length_lo = 0\n'
        yield '\n'
        
        # parse_byte method
        yield f'    def parse_byte(self, byte: int) -> FrameMsgInfo:\n'
        yield f'        """\n'
        yield f'        Parse a single byte\n'
        yield f'        \n'
        yield f'        Returns:\n'
        yield f'            FrameMsgInfo with valid=True when a complete valid message is received\n'
        yield f'        """\n'
        yield f'        result = FrameMsgInfo()\n\n'
        
        # State machine
        if fmt.start_bytes:
            for i, (sb_name, sb_value) in enumerate(fmt.start_bytes):
                state_name = f'LOOKING_FOR_START{i + 1}' if len(fmt.start_bytes) > 1 else 'LOOKING_FOR_START'
                const_name = f'self.START_BYTE{i + 1}' if len(fmt.start_bytes) > 1 else 'self.START_BYTE'
                
                # First state uses 'if', subsequent states use 'elif'
                keyword = 'if' if i == 0 else 'elif'
                yield f'        {keyword} self.state == {class_name}ParserState.{state_name}:\n'
                yield f'            if byte == {const_name}:\n'
                
                if i == 0:
                    yield f'                self.buffer = [byte]\n'
                else:
                    yield f'                self.buffer.append(byte)\n'
                    
                if i + 1 < len(fmt.start_bytes):
                    next_state = f'LOOKING_FOR_START{i + 2}'
                else:
                    next_state = 'GETTING_MSG_ID'
                yield f'                self.state = {class_name}ParserState.{next_state}\n'
                
                # Handle seeing start byte 1 while looking for later bytes
                # This code only runs when len(fmt.start_bytes) > 1 (i.e., i > 0 is only possible with 2+ start bytes)
                if i > 0:
                    yield f'            elif byte == self.START_BYTE1:\n'
                    yield f'                self.buffer = [byte]\n'
                    yield f'                self.state = {class_name}ParserState.LOOKING_FOR_START2\n'
                    yield f'            else:\n'
                    yield f'                self.state = {class_name}ParserState.LOOKING_FOR_START1\n'
                yield '\n'
        
        # GETTING_MSG_ID state
        if fmt.start_bytes:
            yield f'        elif self.state == {class_name}ParserState.GETTING_MSG_ID:\n'
        else:
            yield f'        if self.state == {class_name}ParserState.GETTING_MSG_ID:\n'
        yield f'            self.buffer.append(byte)\n'
        yield f'            self.msg_id = byte\n'
        
        if fmt.has_length:
            yield f'            self.state = {class_name}ParserState.GETTING_LENGTH\n'
        else:
            yield f'            if self.get_msg_length:\n'
            yield f'                msg_length = self.get_msg_length(byte)\n'
            yield f'                if msg_length is not None:\n'
            yield f'                    self.packet_size = self.OVERHEAD + msg_length\n'
            yield f'                    self.state = {class_name}ParserState.GETTING_PAYLOAD\n'
            yield f'                else:\n'
            reset_state = 'LOOKING_FOR_START1' if len(fmt.start_bytes) > 1 else ('LOOKING_FOR_START' if fmt.start_bytes else 'GETTING_MSG_ID')
            yield f'                    self.state = {class_name}ParserState.{reset_state}\n'
            yield f'            else:\n'
            yield f'                self.state = {class_name}ParserState.{reset_state}\n'
        yield '\n'
        
        # GETTING_LENGTH state (if applicable)
        if fmt.has_length:
            yield f'        elif self.state == {class_name}ParserState.GETTING_LENGTH:\n'
            yield f'            self.buffer.append(byte)\n'
            if fmt.length_bytes == 1:
                yield f'            self.msg_length = byte\n'
                yield f'            self.packet_size = self.OVERHEAD + self.msg_length\n'
                yield f'            self.state = {class_name}ParserState.GETTING_PAYLOAD\n'
            else:
                yield f'            if len(self.buffer) == {len(fmt.start_bytes) + 2}:\n'
                yield f'                self.length_lo = byte\n'
                yield f'            else:\n'
                yield f'                self.msg_length = self.length_lo | (byte << 8)\n'
                yield f'                self.packet_size = self.OVERHEAD + self.msg_length\n'
                yield f'                self.state = {class_name}ParserState.GETTING_PAYLOAD\n'
            yield '\n'
        
        # GETTING_PAYLOAD state
        yield f'        elif self.state == {class_name}ParserState.GETTING_PAYLOAD:\n'
        yield f'            self.buffer.append(byte)\n\n'
        yield f'            if len(self.buffer) >= self.packet_size:\n'
        
        if fmt.has_crc:
            yield f'                # Validate checksum\n'
            yield f'                msg_length = self.packet_size - self.OVERHEAD\n'
            crc_start = len(fmt.start_bytes)
            crc_len = f'msg_length + 1'
            if fmt.has_length:
                crc_len += f' + {fmt.length_bytes}'
            yield f'                ck = fletcher_checksum(self.buffer, {crc_start}, {crc_start} + {crc_len})\n'
            yield f'                if ck[0] == self.buffer[-2] and ck[1] == self.buffer[-1]:\n'
            yield f'                    result.valid = True\n'
            yield f'                    result.msg_id = self.msg_id\n'
            yield f'                    result.msg_len = msg_length\n'
            yield f'                    result.msg_data = bytes(self.buffer[self.HEADER_SIZE:self.packet_size - self.FOOTER_SIZE])\n'
        else:
            yield f'                result.valid = True\n'
            yield f'                result.msg_id = self.msg_id\n'
            yield f'                result.msg_len = self.packet_size - self.OVERHEAD\n'
            yield f'                result.msg_data = bytes(self.buffer[self.HEADER_SIZE:])\n'
        
        reset_state = 'LOOKING_FOR_START1' if len(fmt.start_bytes) > 1 else ('LOOKING_FOR_START' if fmt.start_bytes else 'GETTING_MSG_ID')
        yield f'                self.state = {class_name}ParserState.{reset_state}\n'
        yield '\n'
        yield f'        return result\n\n'
        
        # encode method
        yield f'    def encode(self, msg_id: int, msg: bytes) -> bytes:\n'
        yield f'        """\n'
        yield f'        Encode a message with {name} format\n'
        yield f'        \n'
        yield f'        Args:\n'
        yield f'            msg_id: Message ID\n'
        yield f'            msg: Message data bytes\n'
        yield f'        \n'
        yield f'        Returns:\n'
        yield f'            Encoded frame as bytes\n'
        yield f'        """\n'
        yield f'        output = []\n'
        
        # Write header
        for i, (sb_name, sb_value) in enumerate(fmt.start_bytes):
            const_name = f'self.START_BYTE{i + 1}' if len(fmt.start_bytes) > 1 else 'self.START_BYTE'
            yield f'        output.append({const_name})\n'
        yield f'        output.append(msg_id)\n'
        
        if fmt.has_length:
            if fmt.length_bytes == 1:
                yield f'        output.append(len(msg) & 0xFF)\n'
            else:
                yield f'        output.append(len(msg) & 0xFF)\n'
                yield f'        output.append((len(msg) >> 8) & 0xFF)\n'
        
        yield f'        output.extend(msg)\n'
        
        if fmt.has_crc:
            crc_start = len(fmt.start_bytes)
            crc_len = 'len(msg) + 1'
            if fmt.has_length:
                crc_len += f' + {fmt.length_bytes}'
            yield f'        ck = fletcher_checksum(output, {crc_start}, {crc_start} + {crc_len})\n'
            yield f'        output.append(ck[0])\n'
            yield f'        output.append(ck[1])\n'
        
        yield f'        return bytes(output)\n\n'
        
        # encode_msg method (for message objects with msg_id and pack())
        yield f'    def encode_msg(self, msg) -> bytes:\n'
        yield f'        """Encode a message object (must have msg_id and pack() method)"""\n'
        yield f'        return self.encode(msg.msg_id, msg.pack())\n\n'
        
        # validate_packet method
        yield f'    @staticmethod\n'
        yield f'    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:\n'
        yield f'        """\n'
        yield f'        Validate a complete {name} packet in a buffer\n'
        yield f'        \n'
        yield f'        Args:\n'
        yield f'            buffer: Buffer containing the complete packet\n'
        yield f'        \n'
        yield f'        Returns:\n'
        yield f'            FrameMsgInfo with valid=True if packet is valid\n'
        yield f'        """\n'
        yield f'        result = FrameMsgInfo()\n\n'
        yield f'        if len(buffer) < {class_name}.OVERHEAD:\n'
        yield f'            return result\n\n'
        
        # Check start bytes
        for i, (sb_name, sb_value) in enumerate(fmt.start_bytes):
            const_name = f'{class_name}.START_BYTE{i + 1}' if len(fmt.start_bytes) > 1 else f'{class_name}.START_BYTE'
            yield f'        if buffer[{i}] != {const_name}:\n'
            yield f'            return result\n'
        
        yield f'\n        msg_length = len(buffer) - {class_name}.OVERHEAD\n\n'
        
        if fmt.has_crc:
            crc_start = len(fmt.start_bytes)
            crc_len = 'msg_length + 1'
            if fmt.has_length:
                crc_len += f' + {fmt.length_bytes}'
            yield f'        # Validate checksum\n'
            yield f'        ck = fletcher_checksum(buffer, {crc_start}, {crc_start} + {crc_len})\n'
            yield f'        if ck[0] == buffer[-2] and ck[1] == buffer[-1]:\n'
            yield f'            result.valid = True\n'
            yield f'            result.msg_id = buffer[{len(fmt.start_bytes)}]\n'
            yield f'            result.msg_len = msg_length\n'
            yield f'            result.msg_data = bytes(buffer[{class_name}.HEADER_SIZE:len(buffer) - {class_name}.FOOTER_SIZE])\n'
        else:
            yield f'        result.valid = True\n'
            yield f'        result.msg_id = buffer[{len(fmt.start_bytes)}]\n'
            yield f'        result.msg_len = msg_length\n'
            yield f'        result.msg_data = bytes(buffer[{class_name}.HEADER_SIZE:])\n'
        
        yield f'\n        return result\n'


def generate_py_frame_parsers(formats):
    """Generate Python frame parser code from frame format definitions"""
    return ''.join(FrameParserPyGen.generate(formats))


def generate_py_frame_parsers_multi(formats):
    """
    Generate multiple Python files for frame parsers.

    Returns a dictionary mapping filename to content:
    - frame_base.py: Base utilities (checksum, FrameMsgInfo, FrameFormatType)
    - {snake_name}.py: Individual frame format files
    - __init__.py: Package init that exports all frame formats
    """
    files = {}

    # Generate base file
    files['frame_base.py'] = ''.join(FrameParserPyGen.generate_base(formats))

    # Generate individual frame format files
    for fmt in formats:
        snake_name = camel_to_snake(fmt.name)
        files[f'{snake_name}.py'] = ''.join(FrameParserPyGen.generate_format_file(fmt))

    # Generate __init__.py
    files['__init__.py'] = ''.join(FrameParserPyGen.generate_init(formats))

    return files
