/* Automatically generated struct frame header */
/* Generated by nanopb-1.0.0-dev */

import { Struct, typed, type ExtractType } from 'typed-struct';
import { struct_frame_buffer } from './struct_frame_types';
import { msg_encode, msg_reserve, msg_finish } from './struct_frame';

/* Enum definitions */
export enum biostream_AdcSamplingFrequency {
    biostream_FREQ_1000 = 0,
    biostream_FREQ_2000 = 1,
    biostream_FREQ_4000 = 2,
    biostream_FREQ_8000 = 3,
    biostream_FREQ_16000 = 4
}

export enum biostream_TransImpedanceGain {
    biostream_R_10 = 0,
    biostream_R_100 = 1,
    biostream_R_1k = 2,
    biostream_R_10k = 3
}

/* Struct definitions */
export const biostream_RawData = new Struct('biostream_RawData') 
    .Float32LE('refV')
    .Float32LE('drnC')
    .Float32LE('srcV')
    .Float32LE('drnV')
    .Float32LE('gteV')
    .Float32LE('phsV')
    .Float32LE('gteC')
    .Float32LE('temp')
    .Float32LE('time')
    .compile();

export const biostream_RawData_max_size = 36;
export const biostream_RawData_msgid = 1
export function biostream_RawData_encode(buffer: struct_frame_buffer, msg: ExtractType<typeof biostream_RawData>) {
    msg_encode(buffer, msg, biostream_RawData_msgid)
}
export function biostream_RawData_reserve(buffer: struct_frame_buffer) {
    let msg_buffer = msg_reserve(buffer, biostream_RawData_msgid, biostream_RawData_max_size);
    if (msg_buffer){
        return new biostream_RawData(msg_buffer)
    }
    return;
}
export function biostream_RawData_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}


export const biostream_AdcCommand = new Struct('biostream_AdcCommand') 
    .Boolean8('enable')
    .UInt8('sampligFreq', typed<biostream_AdcSamplingFrequency>())
    .UInt8('overSamplingRate')
    .UInt8('drainRes', typed<biostream_TransImpedanceGain>())
    .UInt8('gateRes', typed<biostream_TransImpedanceGain>())
    .compile();

export const biostream_AdcCommand_max_size = 5;
export const biostream_AdcCommand_msgid = 2
export function biostream_AdcCommand_encode(buffer: struct_frame_buffer, msg: ExtractType<typeof biostream_AdcCommand>) {
    msg_encode(buffer, msg, biostream_AdcCommand_msgid)
}
export function biostream_AdcCommand_reserve(buffer: struct_frame_buffer) {
    let msg_buffer = msg_reserve(buffer, biostream_AdcCommand_msgid, biostream_AdcCommand_max_size);
    if (msg_buffer){
        return new biostream_AdcCommand(msg_buffer)
    }
    return;
}
export function biostream_AdcCommand_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}



export function get_message_length(msg_id : number){
 switch (msg_id)
 {
  case biostream_RawData_msgid: return biostream_RawData_max_size;
  case biostream_AdcCommand_msgid: return biostream_AdcCommand_max_size;
  default: break;
 } return 0;
}
