/* Automatically generated struct frame header */
/* Generated by 0.0.1 at Tue Aug 12 03:02:59 2025. */

const typed_struct = require('typed-struct')
const ExtractType = typeof typed_struct.ExtractType;
const type = typeof typed_struct.ExtractType;

import { struct_frame_buffer } from './struct_frame_types';
import { msg_encode, msg_reserve, msg_finish } from './struct_frame';

/* Enum definitions */
export enum myl_vehicletype {
    UNSPECIFIED = 0,
    ROVER = 1,
    BOAT = 2,
    FW = 3,
    MR = 4,
    CAR = 5
}

/* Struct definitions */
export const myl_vehicle_position = new typed_struct.Struct('myl_vehicle_position') 
    .Float64LE('lat')
    .Float64LE('lon')
    .Float32LE('alt')
    .compile();

export const myl_vehicle_position_max_size = 20;
export const myl_vehicle_position_msgid = 1
export function myl_vehicle_position_encode(buffer: struct_frame_buffer, msg: any) {
    msg_encode(buffer, msg, myl_vehicle_position_msgid)
}
export function myl_vehicle_position_reserve(buffer: struct_frame_buffer) {
    const msg_buffer = msg_reserve(buffer, myl_vehicle_position_msgid, myl_vehicle_position_max_size);
    if (msg_buffer){
        return new myl_vehicle_position(msg_buffer)
    }
    return;
}
export function myl_vehicle_position_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}


//Used for sending robot pose
export const myl_vehicle_pose = new typed_struct.Struct('myl_vehicle_pose') 
//Used for sending roll
    .Float32LE('roll')
// Used for sending pitch
    .Float32LE('pitch')
    .Float32LE('yaw')
    .Float32LE('roll_rate')
    .Float32LE('pitch_rate')
    .Float32LE('yaw_rate')
    .Int16LE('test')
    .compile();

export const myl_vehicle_pose_max_size = 26;
export const myl_vehicle_pose_msgid = 2
export function myl_vehicle_pose_encode(buffer: struct_frame_buffer, msg: any) {
    msg_encode(buffer, msg, myl_vehicle_pose_msgid)
}
export function myl_vehicle_pose_reserve(buffer: struct_frame_buffer) {
    const msg_buffer = msg_reserve(buffer, myl_vehicle_pose_msgid, myl_vehicle_pose_max_size);
    if (msg_buffer){
        return new myl_vehicle_pose(msg_buffer)
    }
    return;
}
export function myl_vehicle_pose_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}


export const myl_vehicle_heartbeat = new typed_struct.Struct('myl_vehicle_heartbeat') 
    .myl_vehicle_type('type')
    .Int32LE('id')
    .compile();

export const myl_vehicle_heartbeat_max_size = 5;
export const myl_vehicle_heartbeat_msgid = 3
export function myl_vehicle_heartbeat_encode(buffer: struct_frame_buffer, msg: any) {
    msg_encode(buffer, msg, myl_vehicle_heartbeat_msgid)
}
export function myl_vehicle_heartbeat_reserve(buffer: struct_frame_buffer) {
    const msg_buffer = msg_reserve(buffer, myl_vehicle_heartbeat_msgid, myl_vehicle_heartbeat_max_size);
    if (msg_buffer){
        return new myl_vehicle_heartbeat(msg_buffer)
    }
    return;
}
export function myl_vehicle_heartbeat_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}


export const myl_vehicle_heartbeat2 = new typed_struct.Struct('myl_vehicle_heartbeat2') 
    .Float32LE('test')
    .Int32LE('id3')
    .compile();

export const myl_vehicle_heartbeat2_max_size = 8;
export const myl_vehicle_heartbeat2_msgid = 4
export function myl_vehicle_heartbeat2_encode(buffer: struct_frame_buffer, msg: any) {
    msg_encode(buffer, msg, myl_vehicle_heartbeat2_msgid)
}
export function myl_vehicle_heartbeat2_reserve(buffer: struct_frame_buffer) {
    const msg_buffer = msg_reserve(buffer, myl_vehicle_heartbeat2_msgid, myl_vehicle_heartbeat2_max_size);
    if (msg_buffer){
        return new myl_vehicle_heartbeat2(msg_buffer)
    }
    return;
}
export function myl_vehicle_heartbeat2_finish(buffer: struct_frame_buffer) {
    msg_finish(buffer);
}



export function get_message_length(msg_id : number){
 switch (msg_id)
 {
  case myl_vehicle_position_msgid: return myl_vehicle_position_max_size;
  case myl_vehicle_pose_msgid: return myl_vehicle_pose_max_size;
  case myl_vehicle_heartbeat_msgid: return myl_vehicle_heartbeat_max_size;
  case myl_vehicle_heartbeat2_msgid: return myl_vehicle_heartbeat2_max_size;
  default: break;
 } return 0;
}
