# Automatically generated frame parser
# Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

from enum import Enum
from typing import Callable, List, Union
from .frame_base import (
    FrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
)

# =============================================================================
# BasicMultiSystemStream Frame Format
# =============================================================================

class BasicMultiSystemStreamParserState(Enum):
    LOOKING_FOR_START1 = 0
    LOOKING_FOR_START2 = 1
    GETTING_MSG_ID = 2
    GETTING_LENGTH = 3
    GETTING_PAYLOAD = 4


class BasicMultiSystemStream:
    """
    BasicMultiSystemStream - Frame format parser and encoder
    
    Format: [START_BYTE1=0x90] [START_BYTE2=0x77] [MSG_ID] [LEN] [MSG...] [CRC1] [CRC2]
    """

    START_BYTE1 = 0x90
    START_BYTE2 = 0x77
    HEADER_SIZE = 7
    FOOTER_SIZE = 2
    OVERHEAD = 9
    LENGTH_BYTES = 1

    def __init__(self, get_msg_length: Callable[[int], int] = None):
        """
        Initialize the BasicMultiSystemStream parser
        
        Args:
            get_msg_length: Callback function to get message length from msg_id
                            Required for formats without a length field
        """
        self.get_msg_length = get_msg_length
        self.reset()

    def reset(self):
        """Reset parser state"""
        self.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1
        self.buffer = []
        self.packet_size = 0
        self.msg_id = 0
        self.msg_length = 0

    def parse_byte(self, byte: int) -> FrameMsgInfo:
        """
        Parse a single byte
        
        Returns:
            FrameMsgInfo with valid=True when a complete valid message is received
        """
        result = FrameMsgInfo()

        if self.state == BasicMultiSystemStreamParserState.LOOKING_FOR_START1:
            if byte == self.START_BYTE1:
                self.buffer = [byte]
                self.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START2

        elif self.state == BasicMultiSystemStreamParserState.LOOKING_FOR_START2:
            if byte == self.START_BYTE2:
                self.buffer.append(byte)
                self.state = BasicMultiSystemStreamParserState.GETTING_MSG_ID
            elif byte == self.START_BYTE1:
                self.buffer = [byte]
                self.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START2
            else:
                self.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1

        elif self.state == BasicMultiSystemStreamParserState.GETTING_MSG_ID:
            self.buffer.append(byte)
            self.msg_id = byte
            self.state = BasicMultiSystemStreamParserState.GETTING_LENGTH

        elif self.state == BasicMultiSystemStreamParserState.GETTING_LENGTH:
            self.buffer.append(byte)
            self.msg_length = byte
            self.packet_size = self.OVERHEAD + self.msg_length
            self.state = BasicMultiSystemStreamParserState.GETTING_PAYLOAD

        elif self.state == BasicMultiSystemStreamParserState.GETTING_PAYLOAD:
            self.buffer.append(byte)

            if len(self.buffer) >= self.packet_size:
                # Use shared payload validation with CRC
                result = validate_payload_with_crc(self.buffer, self.HEADER_SIZE, 1, 2)
                self.state = BasicMultiSystemStreamParserState.LOOKING_FOR_START1

        return result

    def encode(self, msg_id: int, msg: bytes) -> bytes:
        """
        Encode a message with BasicMultiSystemStream format
        
        Args:
            msg_id: Message ID
            msg: Message data bytes
        
        Returns:
            Encoded frame as bytes
        """
        output = []
        output.append(self.START_BYTE1)
        output.append(self.START_BYTE2)
        # Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 1, 2)
        return bytes(output)

    def encode_msg(self, msg) -> bytes:
        """Encode a message object (must have msg_id and pack() method)"""
        return self.encode(msg.msg_id, msg.pack())

    @staticmethod
    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:
        """
        Validate a complete BasicMultiSystemStream packet in a buffer
        
        Args:
            buffer: Buffer containing the complete packet
        
        Returns:
            FrameMsgInfo with valid=True if packet is valid
        """
        if len(buffer) < BasicMultiSystemStream.OVERHEAD:
            return FrameMsgInfo()

        if buffer[0] != BasicMultiSystemStream.START_BYTE1:
            return FrameMsgInfo()
        if buffer[1] != BasicMultiSystemStream.START_BYTE2:
            return FrameMsgInfo()

        # Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, BasicMultiSystemStream.HEADER_SIZE, 1, 2)
