# Automatically generated frame parser
# Generated by 0.0.1 at Thu Dec  4 18:04:46 2025.

from enum import Enum
from typing import Callable, List, Union
from .frame_base import FrameMsgInfo, fletcher_checksum

# =============================================================================
# BasicExtended Frame Format
# =============================================================================

class BasicExtendedParserState(Enum):
    LOOKING_FOR_START1 = 0
    LOOKING_FOR_START2 = 1
    GETTING_MSG_ID = 2
    GETTING_LENGTH = 3
    GETTING_PAYLOAD = 4


class BasicExtended:
    """
    BasicExtended - Frame format parser and encoder
    
    Format: [START_BYTE1=0x90] [START_BYTE2=0x74] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]
    """

    START_BYTE1 = 0x90
    START_BYTE2 = 0x74
    HEADER_SIZE = 6
    FOOTER_SIZE = 2
    OVERHEAD = 8
    LENGTH_BYTES = 2

    def __init__(self, get_msg_length: Callable[[int], int] = None):
        """
        Initialize the BasicExtended parser
        
        Args:
            get_msg_length: Callback function to get message length from msg_id
                            Required for formats without a length field
        """
        self.get_msg_length = get_msg_length
        self.reset()

    def reset(self):
        """Reset parser state"""
        self.state = BasicExtendedParserState.LOOKING_FOR_START1
        self.buffer = []
        self.packet_size = 0
        self.msg_id = 0
        self.msg_length = 0
        self.length_lo = 0

    def parse_byte(self, byte: int) -> FrameMsgInfo:
        """
        Parse a single byte
        
        Returns:
            FrameMsgInfo with valid=True when a complete valid message is received
        """
        result = FrameMsgInfo()

        if self.state == BasicExtendedParserState.LOOKING_FOR_START1:
            if byte == self.START_BYTE1:
                self.buffer = [byte]
                self.state = BasicExtendedParserState.LOOKING_FOR_START2

        elif self.state == BasicExtendedParserState.LOOKING_FOR_START2:
            if byte == self.START_BYTE2:
                self.buffer.append(byte)
                self.state = BasicExtendedParserState.GETTING_MSG_ID
            elif byte == self.START_BYTE1:
                self.buffer = [byte]
                self.state = BasicExtendedParserState.LOOKING_FOR_START2
            else:
                self.state = BasicExtendedParserState.LOOKING_FOR_START1

        elif self.state == BasicExtendedParserState.GETTING_MSG_ID:
            self.buffer.append(byte)
            self.msg_id = byte
            self.state = BasicExtendedParserState.GETTING_LENGTH

        elif self.state == BasicExtendedParserState.GETTING_LENGTH:
            self.buffer.append(byte)
            if len(self.buffer) == 4:
                self.length_lo = byte
            else:
                self.msg_length = self.length_lo | (byte << 8)
                self.packet_size = self.OVERHEAD + self.msg_length
                self.state = BasicExtendedParserState.GETTING_PAYLOAD

        elif self.state == BasicExtendedParserState.GETTING_PAYLOAD:
            self.buffer.append(byte)

            if len(self.buffer) >= self.packet_size:
                # Validate checksum
                msg_length = self.packet_size - self.OVERHEAD
                ck = fletcher_checksum(self.buffer, 2, 2 + msg_length + 1 + 2)
                if ck[0] == self.buffer[-2] and ck[1] == self.buffer[-1]:
                    result.valid = True
                    result.msg_id = self.msg_id
                    result.msg_len = msg_length
                    result.msg_data = bytes(self.buffer[self.HEADER_SIZE:self.packet_size - self.FOOTER_SIZE])
                self.state = BasicExtendedParserState.LOOKING_FOR_START1

        return result

    def encode(self, msg_id: int, msg: bytes) -> bytes:
        """
        Encode a message with BasicExtended format
        
        Args:
            msg_id: Message ID
            msg: Message data bytes
        
        Returns:
            Encoded frame as bytes
        """
        output = []
        output.append(self.START_BYTE1)
        output.append(self.START_BYTE2)
        output.append(msg_id)
        output.append(len(msg) & 0xFF)
        output.append((len(msg) >> 8) & 0xFF)
        output.extend(msg)
        ck = fletcher_checksum(output, 2, 2 + len(msg) + 1 + 2)
        output.append(ck[0])
        output.append(ck[1])
        return bytes(output)

    def encode_msg(self, msg) -> bytes:
        """Encode a message object (must have msg_id and pack() method)"""
        return self.encode(msg.msg_id, msg.pack())

    @staticmethod
    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:
        """
        Validate a complete BasicExtended packet in a buffer
        
        Args:
            buffer: Buffer containing the complete packet
        
        Returns:
            FrameMsgInfo with valid=True if packet is valid
        """
        result = FrameMsgInfo()

        if len(buffer) < BasicExtended.OVERHEAD:
            return result

        if buffer[0] != BasicExtended.START_BYTE1:
            return result
        if buffer[1] != BasicExtended.START_BYTE2:
            return result

        msg_length = len(buffer) - BasicExtended.OVERHEAD

        # Validate checksum
        ck = fletcher_checksum(buffer, 2, 2 + msg_length + 1 + 2)
        if ck[0] == buffer[-2] and ck[1] == buffer[-1]:
            result.valid = True
            result.msg_id = buffer[2]
            result.msg_len = msg_length
            result.msg_data = bytes(buffer[BasicExtended.HEADER_SIZE:len(buffer) - BasicExtended.FOOTER_SIZE])

        return result
