# Automatically generated frame parser
# Generated by 0.0.1 at Wed Dec  3 17:57:16 2025.

from enum import Enum
from typing import Callable, List, Union
from .frame_base import FrameMsgInfo, fletcher_checksum

# =============================================================================
# MinimalFrameWithLenNoCrc Frame Format
# =============================================================================

class MinimalFrameWithLenNoCrcParserState(Enum):
    GETTING_MSG_ID = 0
    GETTING_LENGTH = 1
    GETTING_PAYLOAD = 2


class MinimalFrameWithLenNoCrc:
    """
    MinimalFrameWithLenNoCrc - Frame format parser and encoder
    
    Format: [MSG_ID] [LEN] [MSG...]
    """

    HEADER_SIZE = 2
    FOOTER_SIZE = 0
    OVERHEAD = 2
    LENGTH_BYTES = 1

    def __init__(self, get_msg_length: Callable[[int], int] = None):
        """
        Initialize the MinimalFrameWithLenNoCrc parser
        
        Args:
            get_msg_length: Callback function to get message length from msg_id
                            Required for formats without a length field
        """
        self.get_msg_length = get_msg_length
        self.reset()

    def reset(self):
        """Reset parser state"""
        self.state = MinimalFrameWithLenNoCrcParserState.GETTING_MSG_ID
        self.buffer = []
        self.packet_size = 0
        self.msg_id = 0
        self.msg_length = 0

    def parse_byte(self, byte: int) -> FrameMsgInfo:
        """
        Parse a single byte
        
        Returns:
            FrameMsgInfo with valid=True when a complete valid message is received
        """
        result = FrameMsgInfo()

        if self.state == MinimalFrameWithLenNoCrcParserState.GETTING_MSG_ID:
            self.buffer.append(byte)
            self.msg_id = byte
            self.state = MinimalFrameWithLenNoCrcParserState.GETTING_LENGTH

        elif self.state == MinimalFrameWithLenNoCrcParserState.GETTING_LENGTH:
            self.buffer.append(byte)
            self.msg_length = byte
            self.packet_size = self.OVERHEAD + self.msg_length
            self.state = MinimalFrameWithLenNoCrcParserState.GETTING_PAYLOAD

        elif self.state == MinimalFrameWithLenNoCrcParserState.GETTING_PAYLOAD:
            self.buffer.append(byte)

            if len(self.buffer) >= self.packet_size:
                result.valid = True
                result.msg_id = self.msg_id
                result.msg_len = self.packet_size - self.OVERHEAD
                result.msg_data = bytes(self.buffer[self.HEADER_SIZE:])
                self.state = MinimalFrameWithLenNoCrcParserState.GETTING_MSG_ID

        return result

    def encode(self, msg_id: int, msg: bytes) -> bytes:
        """
        Encode a message with MinimalFrameWithLenNoCrc format
        
        Args:
            msg_id: Message ID
            msg: Message data bytes
        
        Returns:
            Encoded frame as bytes
        """
        output = []
        output.append(msg_id)
        output.append(len(msg) & 0xFF)
        output.extend(msg)
        return bytes(output)

    def encode_msg(self, msg) -> bytes:
        """Encode a message object (must have msg_id and pack() method)"""
        return self.encode(msg.msg_id, msg.pack())

    @staticmethod
    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:
        """
        Validate a complete MinimalFrameWithLenNoCrc packet in a buffer
        
        Args:
            buffer: Buffer containing the complete packet
        
        Returns:
            FrameMsgInfo with valid=True if packet is valid
        """
        result = FrameMsgInfo()

        if len(buffer) < MinimalFrameWithLenNoCrc.OVERHEAD:
            return result


        msg_length = len(buffer) - MinimalFrameWithLenNoCrc.OVERHEAD

        result.valid = True
        result.msg_id = buffer[0]
        result.msg_len = msg_length
        result.msg_data = bytes(buffer[MinimalFrameWithLenNoCrc.HEADER_SIZE:])

        return result
