# Automatically generated frame parser
# Generated by 0.0.1 at Fri Dec 19 18:24:29 2025.

try:
    from .frame_base import (
        FrameParserConfig, create_frame_parser_class, GenericParserState,
    )
except ImportError:
    from frame_base import (
        FrameParserConfig, create_frame_parser_class, GenericParserState,
    )

# =============================================================================
# TinyExtendedMultiSystemStream Frame Format Configuration
# =============================================================================

# Configuration for TinyExtendedMultiSystemStream frame format
TinyExtendedMultiSystemStreamConfig = FrameParserConfig(
    name='TinyExtendedMultiSystemStream',
    start_bytes=(0x78,),
    header_size=8,
    footer_size=2,
    has_length=True,
    length_bytes=2,
    has_crc=True,
)

"""
TinyExtendedMultiSystemStream - Frame format parser and encoder

Format: [START_BYTE=0x78] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]

This class is generated using create_frame_parser_class() for code reuse.
"""
TinyExtendedMultiSystemStream = create_frame_parser_class(TinyExtendedMultiSystemStreamConfig)

# Parser state alias for backward compatibility
TinyExtendedMultiSystemStreamParserState = GenericParserState
