# Automatically generated frame parser
# Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

from enum import Enum
from typing import Callable, List, Union
from .frame_base import (
    FrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
)

# =============================================================================
# TinySeq Frame Format
# =============================================================================

class TinySeqParserState(Enum):
    LOOKING_FOR_START = 0
    GETTING_MSG_ID = 1
    GETTING_LENGTH = 2
    GETTING_PAYLOAD = 3


class TinySeq:
    """
    TinySeq - Frame format parser and encoder
    
    Format: [START_BYTE=0x76] [MSG_ID] [LEN] [MSG...] [CRC1] [CRC2]
    """

    START_BYTE = 0x76
    HEADER_SIZE = 4
    FOOTER_SIZE = 2
    OVERHEAD = 6
    LENGTH_BYTES = 1

    def __init__(self, get_msg_length: Callable[[int], int] = None):
        """
        Initialize the TinySeq parser
        
        Args:
            get_msg_length: Callback function to get message length from msg_id
                            Required for formats without a length field
        """
        self.get_msg_length = get_msg_length
        self.reset()

    def reset(self):
        """Reset parser state"""
        self.state = TinySeqParserState.LOOKING_FOR_START
        self.buffer = []
        self.packet_size = 0
        self.msg_id = 0
        self.msg_length = 0

    def parse_byte(self, byte: int) -> FrameMsgInfo:
        """
        Parse a single byte
        
        Returns:
            FrameMsgInfo with valid=True when a complete valid message is received
        """
        result = FrameMsgInfo()

        if self.state == TinySeqParserState.LOOKING_FOR_START:
            if byte == self.START_BYTE:
                self.buffer = [byte]
                self.state = TinySeqParserState.GETTING_MSG_ID

        elif self.state == TinySeqParserState.GETTING_MSG_ID:
            self.buffer.append(byte)
            self.msg_id = byte
            self.state = TinySeqParserState.GETTING_LENGTH

        elif self.state == TinySeqParserState.GETTING_LENGTH:
            self.buffer.append(byte)
            self.msg_length = byte
            self.packet_size = self.OVERHEAD + self.msg_length
            self.state = TinySeqParserState.GETTING_PAYLOAD

        elif self.state == TinySeqParserState.GETTING_PAYLOAD:
            self.buffer.append(byte)

            if len(self.buffer) >= self.packet_size:
                # Use shared payload validation with CRC
                result = validate_payload_with_crc(self.buffer, self.HEADER_SIZE, 1, 1)
                self.state = TinySeqParserState.LOOKING_FOR_START

        return result

    def encode(self, msg_id: int, msg: bytes) -> bytes:
        """
        Encode a message with TinySeq format
        
        Args:
            msg_id: Message ID
            msg: Message data bytes
        
        Returns:
            Encoded frame as bytes
        """
        output = []
        output.append(self.START_BYTE)
        # Use shared payload encoding with CRC
        encode_payload_with_crc(output, msg_id, msg, 1, 1)
        return bytes(output)

    def encode_msg(self, msg) -> bytes:
        """Encode a message object (must have msg_id and pack() method)"""
        return self.encode(msg.msg_id, msg.pack())

    @staticmethod
    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:
        """
        Validate a complete TinySeq packet in a buffer
        
        Args:
            buffer: Buffer containing the complete packet
        
        Returns:
            FrameMsgInfo with valid=True if packet is valid
        """
        if len(buffer) < TinySeq.OVERHEAD:
            return FrameMsgInfo()

        if buffer[0] != TinySeq.START_BYTE:
            return FrameMsgInfo()

        # Use shared payload validation with CRC
        return validate_payload_with_crc(buffer, TinySeq.HEADER_SIZE, 1, 1)
