# Automatically generated frame parser
# Generated by 0.0.1 at Thu Dec  4 20:27:20 2025.

from enum import Enum
from typing import Callable, List, Union
from .frame_base import (
    FrameMsgInfo, fletcher_checksum,
    validate_payload_with_crc, validate_payload_minimal,
    encode_payload_with_crc, encode_payload_minimal,
)

# =============================================================================
# TinyMinimal Frame Format
# =============================================================================

class TinyMinimalParserState(Enum):
    LOOKING_FOR_START = 0
    GETTING_MSG_ID = 1
    GETTING_PAYLOAD = 2


class TinyMinimal:
    """
    TinyMinimal - Frame format parser and encoder
    
    Format: [START_BYTE=0x70] [MSG_ID] [MSG...]
    """

    START_BYTE = 0x70
    HEADER_SIZE = 2
    FOOTER_SIZE = 0
    OVERHEAD = 2

    def __init__(self, get_msg_length: Callable[[int], int] = None):
        """
        Initialize the TinyMinimal parser
        
        Args:
            get_msg_length: Callback function to get message length from msg_id
                            Required for formats without a length field
        """
        self.get_msg_length = get_msg_length
        self.reset()

    def reset(self):
        """Reset parser state"""
        self.state = TinyMinimalParserState.LOOKING_FOR_START
        self.buffer = []
        self.packet_size = 0
        self.msg_id = 0

    def parse_byte(self, byte: int) -> FrameMsgInfo:
        """
        Parse a single byte
        
        Returns:
            FrameMsgInfo with valid=True when a complete valid message is received
        """
        result = FrameMsgInfo()

        if self.state == TinyMinimalParserState.LOOKING_FOR_START:
            if byte == self.START_BYTE:
                self.buffer = [byte]
                self.state = TinyMinimalParserState.GETTING_MSG_ID

        elif self.state == TinyMinimalParserState.GETTING_MSG_ID:
            self.buffer.append(byte)
            self.msg_id = byte
            if self.get_msg_length:
                msg_length = self.get_msg_length(byte)
                if msg_length is not None:
                    self.packet_size = self.OVERHEAD + msg_length
                    self.state = TinyMinimalParserState.GETTING_PAYLOAD
                else:
                    self.state = TinyMinimalParserState.LOOKING_FOR_START
            else:
                self.state = TinyMinimalParserState.LOOKING_FOR_START

        elif self.state == TinyMinimalParserState.GETTING_PAYLOAD:
            self.buffer.append(byte)

            if len(self.buffer) >= self.packet_size:
                # Use shared minimal payload validation
                result = validate_payload_minimal(self.buffer, self.HEADER_SIZE)
                self.state = TinyMinimalParserState.LOOKING_FOR_START

        return result

    def encode(self, msg_id: int, msg: bytes) -> bytes:
        """
        Encode a message with TinyMinimal format
        
        Args:
            msg_id: Message ID
            msg: Message data bytes
        
        Returns:
            Encoded frame as bytes
        """
        output = []
        output.append(self.START_BYTE)
        # Use shared minimal payload encoding
        encode_payload_minimal(output, msg_id, msg)
        return bytes(output)

    def encode_msg(self, msg) -> bytes:
        """Encode a message object (must have msg_id and pack() method)"""
        return self.encode(msg.msg_id, msg.pack())

    @staticmethod
    def validate_packet(buffer: Union[bytes, List[int]]) -> FrameMsgInfo:
        """
        Validate a complete TinyMinimal packet in a buffer
        
        Args:
            buffer: Buffer containing the complete packet
        
        Returns:
            FrameMsgInfo with valid=True if packet is valid
        """
        if len(buffer) < TinyMinimal.OVERHEAD:
            return FrameMsgInfo()

        if buffer[0] != TinyMinimal.START_BYTE:
            return FrameMsgInfo()

        # Use shared minimal payload validation
        return validate_payload_minimal(buffer, TinyMinimal.HEADER_SIZE)
