/* Automatically generated frame parser main header */
/* Generated by 0.0.1 at Wed Dec  3 17:57:16 2025. */

#pragma once

/* Base utilities */
#include "frame_base.h"

/* Individual frame format parsers */
#include "minimal_frame.h"
#include "basic_frame.h"
#include "basic_frame_no_crc.h"
#include "tiny_frame.h"
#include "tiny_frame_no_crc.h"
#include "minimal_frame_with_len.h"
#include "minimal_frame_with_len_no_crc.h"
#include "basic_frame_with_len.h"
#include "basic_frame_with_len_no_crc.h"
#include "tiny_frame_with_len.h"
#include "tiny_frame_with_len_no_crc.h"
#include "minimal_frame_with_len16.h"
#include "minimal_frame_with_len16_no_crc.h"
#include "basic_frame_with_len16.h"
#include "basic_frame_with_len16_no_crc.h"
#include "tiny_frame_with_len16.h"
#include "tiny_frame_with_len16_no_crc.h"
#include "basic_frame_with_sys_comp.h"
#include "ubx_frame.h"
#include "mavlink_v1_frame.h"
#include "mavlink_v2_frame.h"
#include "frame_format_config.h"
