/* Automatically generated frame parser base utilities */
/* Generated by 0.0.1 at Thu Dec  4 19:40:48 2025. */

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Frame format type enumeration */
typedef enum FrameFormatType {
    FRAME_FORMAT_TINY_MINIMAL = 0,
    FRAME_FORMAT_TINY_DEFAULT = 1,
    FRAME_FORMAT_TINY_EXTENDED_MSG_IDS = 2,
    FRAME_FORMAT_TINY_EXTENDED_LENGTH = 3,
    FRAME_FORMAT_TINY_EXTENDED = 4,
    FRAME_FORMAT_TINY_SYS_COMP = 5,
    FRAME_FORMAT_TINY_SEQ = 6,
    FRAME_FORMAT_TINY_MULTI_SYSTEM_STREAM = 7,
    FRAME_FORMAT_TINY_EXTENDED_MULTI_SYSTEM_STREAM = 8,
    FRAME_FORMAT_BASIC_MINIMAL = 9,
    FRAME_FORMAT_BASIC_DEFAULT = 10,
    FRAME_FORMAT_BASIC_EXTENDED_MSG_IDS = 11,
    FRAME_FORMAT_BASIC_EXTENDED_LENGTH = 12,
    FRAME_FORMAT_BASIC_EXTENDED = 13,
    FRAME_FORMAT_BASIC_SYS_COMP = 14,
    FRAME_FORMAT_BASIC_SEQ = 15,
    FRAME_FORMAT_BASIC_MULTI_SYSTEM_STREAM = 16,
    FRAME_FORMAT_BASIC_EXTENDED_MULTI_SYSTEM_STREAM = 17,
    FRAME_FORMAT_UBX_FRAME = 18,
    FRAME_FORMAT_MAVLINK_V1_FRAME = 19,
    FRAME_FORMAT_MAVLINK_V2_FRAME = 20,
    FRAME_FORMAT_FRAME_FORMAT_CONFIG = 21,
} FrameFormatType;

/*===========================================================================
 * Checksum Calculation
 *===========================================================================*/

typedef struct frame_checksum {
    uint8_t byte1;
    uint8_t byte2;
} frame_checksum_t;

/**
 * Calculate Fletcher-16 checksum over the given data
 */
static inline frame_checksum_t frame_fletcher_checksum(const uint8_t* data, size_t length) {
    frame_checksum_t ck = {0, 0};
    for (size_t i = 0; i < length; i++) {
        ck.byte1 = (uint8_t)(ck.byte1 + data[i]);
        ck.byte2 = (uint8_t)(ck.byte2 + ck.byte1);
    }
    return ck;
}

/* Parse result */
typedef struct frame_msg_info {
    bool valid;
    uint8_t msg_id;
    size_t msg_len;
    uint8_t* msg_data;
} frame_msg_info_t;
