/* Automatically generated frame parser */
/* Generated by 0.0.1 at Wed Dec  3 17:57:16 2025. */

#pragma once

#include "frame_base.h"

/*===========================================================================
 * MinimalFrame Frame Format
 *===========================================================================*/

/* MinimalFrame constants */
#define MINIMAL_FRAME_HEADER_SIZE    1  /* msg_id */
#define MINIMAL_FRAME_FOOTER_SIZE    2  /* crc(2 bytes) */
#define MINIMAL_FRAME_OVERHEAD       (MINIMAL_FRAME_HEADER_SIZE + MINIMAL_FRAME_FOOTER_SIZE)

/* MinimalFrame parser states */
typedef enum minimal_frame_parser_state {
    MINIMAL_FRAME_GETTING_MSG_ID = 0,
    MINIMAL_FRAME_GETTING_PAYLOAD = 1
} minimal_frame_parser_state_t;

/* MinimalFrame parser state structure */
typedef struct minimal_frame_parser {
    minimal_frame_parser_state_t state;
    uint8_t* buffer;
    size_t buffer_max_size;
    size_t buffer_index;
    size_t packet_size;
    uint8_t msg_id;
    /* User-provided function to get message length from msg_id (for non-length frames) */
    bool (*get_msg_length)(uint8_t msg_id, size_t* length);
} minimal_frame_parser_t;

/* MinimalFrame encode buffer structure */
typedef struct minimal_frame_encode_buffer {
    uint8_t* data;
    size_t max_size;
    size_t size;
    bool in_progress;
    size_t reserved_msg_size;
} minimal_frame_encode_buffer_t;

/**
 * Initialize a MinimalFrame parser
 */
static inline void minimal_frame_parser_init(minimal_frame_parser_t* parser,
                                        uint8_t* buffer, size_t buffer_size,
                                        bool (*get_msg_length)(uint8_t msg_id, size_t* length)) {
    parser->state = MINIMAL_FRAME_GETTING_MSG_ID;
    parser->buffer = buffer;
    parser->buffer_max_size = buffer_size;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
    parser->get_msg_length = get_msg_length;
}

/**
 * Reset MinimalFrame parser state
 */
static inline void minimal_frame_parser_reset(minimal_frame_parser_t* parser) {
    parser->state = MINIMAL_FRAME_GETTING_MSG_ID;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
}

/**
 * Parse a single byte with MinimalFrame format
 * Returns frame_msg_info_t with valid=true when a complete valid message is received
 */
static inline frame_msg_info_t minimal_frame_parse_byte(minimal_frame_parser_t* parser, uint8_t byte) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    switch (parser->state) {
        case MINIMAL_FRAME_GETTING_MSG_ID:
            parser->buffer[parser->buffer_index++] = byte;
            parser->msg_id = byte;
            {
                size_t msg_length = 0;
                if (parser->get_msg_length && parser->get_msg_length(byte, &msg_length)) {
                    parser->packet_size = MINIMAL_FRAME_OVERHEAD + msg_length;
                    if (parser->packet_size <= parser->buffer_max_size) {
                        parser->state = MINIMAL_FRAME_GETTING_PAYLOAD;
                    } else {
                        parser->state = MINIMAL_FRAME_GETTING_MSG_ID;
                    }
                } else {
                    parser->state = MINIMAL_FRAME_GETTING_MSG_ID;
                }
            }
            break;

        case MINIMAL_FRAME_GETTING_PAYLOAD:
            if (parser->buffer_index < parser->buffer_max_size) {
                parser->buffer[parser->buffer_index++] = byte;
            }

            if (parser->buffer_index >= parser->packet_size) {
                /* Validate checksum */
                size_t msg_length = parser->packet_size - MINIMAL_FRAME_OVERHEAD;
                frame_checksum_t ck = frame_fletcher_checksum(
                    parser->buffer + 0, msg_length + 1);

                if (ck.byte1 == parser->buffer[parser->packet_size - 2] &&
                    ck.byte2 == parser->buffer[parser->packet_size - 1]) {
                    result.valid = true;
                    result.msg_id = parser->msg_id;
                    result.msg_len = msg_length;
                    result.msg_data = parser->buffer + MINIMAL_FRAME_HEADER_SIZE;
                }
                parser->state = MINIMAL_FRAME_GETTING_MSG_ID;
            }
            break;
    }

    return result;
}

/**
 * Encode a message with MinimalFrame format
 * Returns the number of bytes written, or 0 on failure
 */
static inline size_t minimal_frame_encode(uint8_t* buffer, size_t buffer_size,
                                     uint8_t msg_id, const uint8_t* msg, size_t msg_size) {
    size_t total_size = MINIMAL_FRAME_OVERHEAD + msg_size;
    if (buffer_size < total_size) {
        return 0;
    }

    buffer[0] = msg_id;

    /* Write message data */
    if (msg_size > 0 && msg != NULL) {
        memcpy(buffer + MINIMAL_FRAME_HEADER_SIZE, msg, msg_size);
    }

    /* Calculate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 0, msg_size + 1);
    buffer[MINIMAL_FRAME_HEADER_SIZE + msg_size] = ck.byte1;
    buffer[MINIMAL_FRAME_HEADER_SIZE + msg_size + 1] = ck.byte2;

    return total_size;
}

/**
 * Validate a complete MinimalFrame packet in a buffer
 */
static inline frame_msg_info_t minimal_frame_validate_packet(const uint8_t* buffer, size_t length) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    if (length < MINIMAL_FRAME_OVERHEAD) {
        return result;
    }


    size_t msg_length = length - MINIMAL_FRAME_OVERHEAD;

    /* Validate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 0, msg_length + 1);
    if (ck.byte1 == buffer[length - 2] && ck.byte2 == buffer[length - 1]) {
        result.valid = true;
        result.msg_id = buffer[0];
        result.msg_len = msg_length;
        result.msg_data = (uint8_t*)(buffer + MINIMAL_FRAME_HEADER_SIZE);
    }

    return result;
}

