/* Automatically generated frame parser */
/* Generated by 0.0.1 at Wed Dec  3 17:57:16 2025. */

#pragma once

#include "frame_base.h"

/*===========================================================================
 * TinyFrameWithLen16 Frame Format
 *===========================================================================*/

/* TinyFrameWithLen16 constants */
#define TINY_FRAME_WITH_LEN16_START_BYTE    0x74
#define TINY_FRAME_WITH_LEN16_HEADER_SIZE    4  /* start_byte + msg_id + length(2) */
#define TINY_FRAME_WITH_LEN16_FOOTER_SIZE    2  /* crc(2 bytes) */
#define TINY_FRAME_WITH_LEN16_OVERHEAD       (TINY_FRAME_WITH_LEN16_HEADER_SIZE + TINY_FRAME_WITH_LEN16_FOOTER_SIZE)

/* TinyFrameWithLen16 parser states */
typedef enum tiny_frame_with_len16_parser_state {
    TINY_FRAME_WITH_LEN16_LOOKING_FOR_START = 0,
    TINY_FRAME_WITH_LEN16_GETTING_MSG_ID = 1,
    TINY_FRAME_WITH_LEN16_GETTING_LENGTH = 2,
    TINY_FRAME_WITH_LEN16_GETTING_PAYLOAD = 3
} tiny_frame_with_len16_parser_state_t;

/* TinyFrameWithLen16 parser state structure */
typedef struct tiny_frame_with_len16_parser {
    tiny_frame_with_len16_parser_state_t state;
    uint8_t* buffer;
    size_t buffer_max_size;
    size_t buffer_index;
    size_t packet_size;
    uint8_t msg_id;
    size_t msg_length;  /* From length field */
    uint8_t length_lo;  /* Low byte for 16-bit length */
    /* User-provided function to get message length from msg_id (for non-length frames) */
    bool (*get_msg_length)(uint8_t msg_id, size_t* length);
} tiny_frame_with_len16_parser_t;

/* TinyFrameWithLen16 encode buffer structure */
typedef struct tiny_frame_with_len16_encode_buffer {
    uint8_t* data;
    size_t max_size;
    size_t size;
    bool in_progress;
    size_t reserved_msg_size;
} tiny_frame_with_len16_encode_buffer_t;

/**
 * Initialize a TinyFrameWithLen16 parser
 */
static inline void tiny_frame_with_len16_parser_init(tiny_frame_with_len16_parser_t* parser,
                                        uint8_t* buffer, size_t buffer_size,
                                        bool (*get_msg_length)(uint8_t msg_id, size_t* length)) {
    parser->state = TINY_FRAME_WITH_LEN16_LOOKING_FOR_START;
    parser->buffer = buffer;
    parser->buffer_max_size = buffer_size;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
    parser->msg_length = 0;
    parser->length_lo = 0;
    parser->get_msg_length = get_msg_length;
}

/**
 * Reset TinyFrameWithLen16 parser state
 */
static inline void tiny_frame_with_len16_parser_reset(tiny_frame_with_len16_parser_t* parser) {
    parser->state = TINY_FRAME_WITH_LEN16_LOOKING_FOR_START;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
    parser->msg_length = 0;
}

/**
 * Parse a single byte with TinyFrameWithLen16 format
 * Returns frame_msg_info_t with valid=true when a complete valid message is received
 */
static inline frame_msg_info_t tiny_frame_with_len16_parse_byte(tiny_frame_with_len16_parser_t* parser, uint8_t byte) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    switch (parser->state) {
        case TINY_FRAME_WITH_LEN16_LOOKING_FOR_START:
            if (byte == TINY_FRAME_WITH_LEN16_START_BYTE) {
                parser->buffer[0] = byte;
                parser->buffer_index = 1;
                parser->state = TINY_FRAME_WITH_LEN16_GETTING_MSG_ID;
            }
            break;

        case TINY_FRAME_WITH_LEN16_GETTING_MSG_ID:
            parser->buffer[parser->buffer_index++] = byte;
            parser->msg_id = byte;
            parser->state = TINY_FRAME_WITH_LEN16_GETTING_LENGTH;
            break;

        case TINY_FRAME_WITH_LEN16_GETTING_LENGTH:
            parser->buffer[parser->buffer_index++] = byte;
            if (parser->buffer_index == 3) {
                parser->length_lo = byte;
            } else {
                parser->msg_length = parser->length_lo | ((size_t)byte << 8);
                parser->packet_size = TINY_FRAME_WITH_LEN16_OVERHEAD + parser->msg_length;
                if (parser->packet_size <= parser->buffer_max_size) {
                    parser->state = TINY_FRAME_WITH_LEN16_GETTING_PAYLOAD;
                } else {
                    parser->state = TINY_FRAME_WITH_LEN16_LOOKING_FOR_START;
                }
            }
            break;

        case TINY_FRAME_WITH_LEN16_GETTING_PAYLOAD:
            if (parser->buffer_index < parser->buffer_max_size) {
                parser->buffer[parser->buffer_index++] = byte;
            }

            if (parser->buffer_index >= parser->packet_size) {
                /* Validate checksum */
                size_t msg_length = parser->packet_size - TINY_FRAME_WITH_LEN16_OVERHEAD;
                frame_checksum_t ck = frame_fletcher_checksum(
                    parser->buffer + 1, msg_length + 1 + 2);

                if (ck.byte1 == parser->buffer[parser->packet_size - 2] &&
                    ck.byte2 == parser->buffer[parser->packet_size - 1]) {
                    result.valid = true;
                    result.msg_id = parser->msg_id;
                    result.msg_len = msg_length;
                    result.msg_data = parser->buffer + TINY_FRAME_WITH_LEN16_HEADER_SIZE;
                }
                parser->state = TINY_FRAME_WITH_LEN16_LOOKING_FOR_START;
            }
            break;
    }

    return result;
}

/**
 * Encode a message with TinyFrameWithLen16 format
 * Returns the number of bytes written, or 0 on failure
 */
static inline size_t tiny_frame_with_len16_encode(uint8_t* buffer, size_t buffer_size,
                                     uint8_t msg_id, const uint8_t* msg, size_t msg_size) {
    size_t total_size = TINY_FRAME_WITH_LEN16_OVERHEAD + msg_size;
    if (buffer_size < total_size) {
        return 0;
    }

    buffer[0] = TINY_FRAME_WITH_LEN16_START_BYTE;
    buffer[1] = msg_id;
    buffer[2] = (uint8_t)(msg_size & 0xFF);
    buffer[3] = (uint8_t)((msg_size >> 8) & 0xFF);

    /* Write message data */
    if (msg_size > 0 && msg != NULL) {
        memcpy(buffer + TINY_FRAME_WITH_LEN16_HEADER_SIZE, msg, msg_size);
    }

    /* Calculate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 1, msg_size + 1 + 2);
    buffer[TINY_FRAME_WITH_LEN16_HEADER_SIZE + msg_size] = ck.byte1;
    buffer[TINY_FRAME_WITH_LEN16_HEADER_SIZE + msg_size + 1] = ck.byte2;

    return total_size;
}

/**
 * Validate a complete TinyFrameWithLen16 packet in a buffer
 */
static inline frame_msg_info_t tiny_frame_with_len16_validate_packet(const uint8_t* buffer, size_t length) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    if (length < TINY_FRAME_WITH_LEN16_OVERHEAD) {
        return result;
    }

    if (buffer[0] != TINY_FRAME_WITH_LEN16_START_BYTE) {
        return result;
    }

    size_t msg_length = length - TINY_FRAME_WITH_LEN16_OVERHEAD;

    /* Validate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 1, msg_length + 1 + 2);
    if (ck.byte1 == buffer[length - 2] && ck.byte2 == buffer[length - 1]) {
        result.valid = true;
        result.msg_id = buffer[1];
        result.msg_len = msg_length;
        result.msg_data = (uint8_t*)(buffer + TINY_FRAME_WITH_LEN16_HEADER_SIZE);
    }

    return result;
}

