/* Automatically generated frame parser */
/* Generated by 0.0.1 at Thu Dec  4 18:04:46 2025. */

#pragma once

#include "frame_base.h"

/*===========================================================================
 * UbxFrame Frame Format
 *===========================================================================*/

/* UbxFrame constants */
#define UBX_FRAME_START_BYTE1    0xB5
#define UBX_FRAME_START_BYTE2    0x62
#define UBX_FRAME_HEADER_SIZE    5  /* sync1 + sync2 + msg_id + length(1) */
#define UBX_FRAME_FOOTER_SIZE    2  /* crc(2 bytes) */
#define UBX_FRAME_OVERHEAD       (UBX_FRAME_HEADER_SIZE + UBX_FRAME_FOOTER_SIZE)

/* UbxFrame parser states */
typedef enum ubx_frame_parser_state {
    UBX_FRAME_LOOKING_FOR_START1 = 0,
    UBX_FRAME_LOOKING_FOR_START2 = 1,
    UBX_FRAME_GETTING_MSG_ID = 2,
    UBX_FRAME_GETTING_LENGTH = 3,
    UBX_FRAME_GETTING_PAYLOAD = 4
} ubx_frame_parser_state_t;

/* UbxFrame parser state structure */
typedef struct ubx_frame_parser {
    ubx_frame_parser_state_t state;
    uint8_t* buffer;
    size_t buffer_max_size;
    size_t buffer_index;
    size_t packet_size;
    uint8_t msg_id;
    size_t msg_length;  /* From length field */
    /* User-provided function to get message length from msg_id (for non-length frames) */
    bool (*get_msg_length)(uint8_t msg_id, size_t* length);
} ubx_frame_parser_t;

/* UbxFrame encode buffer structure */
typedef struct ubx_frame_encode_buffer {
    uint8_t* data;
    size_t max_size;
    size_t size;
    bool in_progress;
    size_t reserved_msg_size;
} ubx_frame_encode_buffer_t;

/**
 * Initialize a UbxFrame parser
 */
static inline void ubx_frame_parser_init(ubx_frame_parser_t* parser,
                                        uint8_t* buffer, size_t buffer_size,
                                        bool (*get_msg_length)(uint8_t msg_id, size_t* length)) {
    parser->state = UBX_FRAME_LOOKING_FOR_START1;
    parser->buffer = buffer;
    parser->buffer_max_size = buffer_size;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
    parser->msg_length = 0;
    parser->get_msg_length = get_msg_length;
}

/**
 * Reset UbxFrame parser state
 */
static inline void ubx_frame_parser_reset(ubx_frame_parser_t* parser) {
    parser->state = UBX_FRAME_LOOKING_FOR_START1;
    parser->buffer_index = 0;
    parser->packet_size = 0;
    parser->msg_id = 0;
    parser->msg_length = 0;
}

/**
 * Parse a single byte with UbxFrame format
 * Returns frame_msg_info_t with valid=true when a complete valid message is received
 */
static inline frame_msg_info_t ubx_frame_parse_byte(ubx_frame_parser_t* parser, uint8_t byte) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    switch (parser->state) {
        case UBX_FRAME_LOOKING_FOR_START1:
            if (byte == UBX_FRAME_START_BYTE1) {
                parser->buffer[0] = byte;
                parser->buffer_index = 1;
                parser->state = UBX_FRAME_LOOKING_FOR_START2;
            }
            break;

        case UBX_FRAME_LOOKING_FOR_START2:
            if (byte == UBX_FRAME_START_BYTE2) {
                parser->buffer[1] = byte;
                parser->buffer_index = 2;
                parser->state = UBX_FRAME_GETTING_MSG_ID;
            } else if (byte == UBX_FRAME_START_BYTE1) {
                parser->buffer[0] = byte;
                parser->buffer_index = 1;
                parser->state = UBX_FRAME_LOOKING_FOR_START2;
            } else {
                parser->state = UBX_FRAME_LOOKING_FOR_START1;
            }
            break;

        case UBX_FRAME_GETTING_MSG_ID:
            parser->buffer[parser->buffer_index++] = byte;
            parser->msg_id = byte;
            parser->state = UBX_FRAME_GETTING_LENGTH;
            break;

        case UBX_FRAME_GETTING_LENGTH:
            parser->buffer[parser->buffer_index++] = byte;
            parser->msg_length = byte;
            parser->packet_size = UBX_FRAME_OVERHEAD + parser->msg_length;
            if (parser->packet_size <= parser->buffer_max_size) {
                parser->state = UBX_FRAME_GETTING_PAYLOAD;
            } else {
                parser->state = UBX_FRAME_LOOKING_FOR_START1;
            }
            break;

        case UBX_FRAME_GETTING_PAYLOAD:
            if (parser->buffer_index < parser->buffer_max_size) {
                parser->buffer[parser->buffer_index++] = byte;
            }

            if (parser->buffer_index >= parser->packet_size) {
                /* Validate checksum */
                size_t msg_length = parser->packet_size - UBX_FRAME_OVERHEAD;
                frame_checksum_t ck = frame_fletcher_checksum(
                    parser->buffer + 2, msg_length + 1 + 1);

                if (ck.byte1 == parser->buffer[parser->packet_size - 2] &&
                    ck.byte2 == parser->buffer[parser->packet_size - 1]) {
                    result.valid = true;
                    result.msg_id = parser->msg_id;
                    result.msg_len = msg_length;
                    result.msg_data = parser->buffer + UBX_FRAME_HEADER_SIZE;
                }
                parser->state = UBX_FRAME_LOOKING_FOR_START1;
            }
            break;
    }

    return result;
}

/**
 * Encode a message with UbxFrame format
 * Returns the number of bytes written, or 0 on failure
 */
static inline size_t ubx_frame_encode(uint8_t* buffer, size_t buffer_size,
                                     uint8_t msg_id, const uint8_t* msg, size_t msg_size) {
    size_t total_size = UBX_FRAME_OVERHEAD + msg_size;
    if (buffer_size < total_size) {
        return 0;
    }

    buffer[0] = UBX_FRAME_START_BYTE1;
    buffer[1] = UBX_FRAME_START_BYTE2;
    buffer[2] = msg_id;
    buffer[3] = (uint8_t)msg_size;

    /* Write message data */
    if (msg_size > 0 && msg != NULL) {
        memcpy(buffer + UBX_FRAME_HEADER_SIZE, msg, msg_size);
    }

    /* Calculate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 2, msg_size + 1 + 1);
    buffer[UBX_FRAME_HEADER_SIZE + msg_size] = ck.byte1;
    buffer[UBX_FRAME_HEADER_SIZE + msg_size + 1] = ck.byte2;

    return total_size;
}

/**
 * Validate a complete UbxFrame packet in a buffer
 */
static inline frame_msg_info_t ubx_frame_validate_packet(const uint8_t* buffer, size_t length) {
    frame_msg_info_t result = {false, 0, 0, NULL};

    if (length < UBX_FRAME_OVERHEAD) {
        return result;
    }

    if (buffer[0] != UBX_FRAME_START_BYTE1) {
        return result;
    }
    if (buffer[1] != UBX_FRAME_START_BYTE2) {
        return result;
    }

    size_t msg_length = length - UBX_FRAME_OVERHEAD;

    /* Validate checksum */
    frame_checksum_t ck = frame_fletcher_checksum(buffer + 2, msg_length + 1 + 1);
    if (ck.byte1 == buffer[length - 2] && ck.byte2 == buffer[length - 1]) {
        result.valid = true;
        result.msg_id = buffer[2];
        result.msg_len = msg_length;
        result.msg_data = (uint8_t*)(buffer + UBX_FRAME_HEADER_SIZE);
    }

    return result;
}

